### ISSUE TITLE
上传图片后的图片路径未更新

### ISSUE THREAD

**Issue by 604587986** [HaoChuan9421/vue-ueditor-wrap#1]
绑定的数据任然是loading图片的路径，只有继续添加内容，或者触发contentchange事件，才能绑定为上传后的图片路径

**Comment by HaoChuan9421** [comment]
不好意思，最近公司比较忙，没看GitHub。不知道你的问题解决没？这个问题的原因在于UEditor的contentchange事件在单图片上传之后不会触发，其实单图片上传还有诸如无法跨越的问题。这些是UEditor本身的缺陷，目前也没有太好的解决方案。不知道你有没有好的建议
<img width="1300" alt="wx20180419-221609 2x" src="https://user-images.githubusercontent.com/28668354/38999485-83f8add8-4424-11e8-89cb-ce06e939d97c.png">

**Comment by HaoChuan9421** [comment]
我刚才看了UEditor的源码，你需要修改一下源码。在第ueditor.all.js的24526行里面加上这么一句，作用就是监听图片加载，加载之后，手动触发一个contentChange事件,如果你为了控制js体积，使用的是ueditor.all.js。自己压缩一下。我已经把修改过的js，放在github上了，你也可以下载
<img width="956" alt="wx20180419-232504 2x" src="https://user-images.githubusercontent.com/28668354/39001454-e911e230-4428-11e8-8a73-f0ebd455de59.png">

**Comment by ah597568204** [comment]
拖拽的图片也是一样，我找到UE.plugin.register('autoupload'  也加了下contentchange

**Comment by HaoChuan9421** [comment]
@ah597568204 现在 v-model 的实现方式主要依赖 MutationObserver API，我自己也试了一下,并存在这种问题，但如果你使用mode="listener"模式，v-model 的实现会依赖 contentChange 事件，可能会存在这个问题，如果确实有的话，你可以给我的这个[仓库](https://github.com/HaoChuan9421/ueditor)提交一个PR，我验证通过后，会更新当前项目的资源文件 assets/downloads
