### ISSUE TITLE
关于跨域的问题

### ISSUE THREAD

**Issue by kevin19a** [HaoChuan9421/vue-ueditor-wrap#100]
我本地开发的时候需要跨域名上传，apache服务器，
header('Access-Control-Allow-Origin:*');
header('Access-Control-Allow-Headers: X-Requested-With,X_Requested_With');
我在我的接口文件使用了上面的代码，但是依旧
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://dev.com/api/file/upload?action=config&callback=bd__editor__oa394p with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
报这个错~折腾了很久了还是没有搞定。不知道有没有大佬可以帮看下的。

**Comment by JinLuhuan** [comment]
CORB 发生时机
当跨域请求回来的数据 MIME type 同跨域标签应有的 MIME 类型不匹配时，浏览器会启动 CORB 保护数据不被泄漏，被保护的数据类型只有 html xml 和 json。很明显 <script> 和 <img> 等跨域标签应有的 MIME type 和 html、xml、json 不一样。

解决方案
在源码ueditor.all.js（正常情况下引用的是ueditor.all.min.js）
找到 dataType:isJsonp?"jsonp":""
修改为 dataType: ""
在服务端接口允许跨域的情况下应该就可以正常请求了
