### ISSUE TITLE
自动排版参数未生效

### ISSUE THREAD

**Issue by hehehai** [HaoChuan9421/vue-ueditor-wrap#102]
**你遇到了什么 BUG**
使用 autotypeset 但是未生效
![image](https://user-images.githubusercontent.com/12692552/72241347-959aeb00-3621-11ea-8cc0-0cdf79d44d4a.png)

![image](https://user-images.githubusercontent.com/12692552/72241395-b5caaa00-3621-11ea-90fc-24d3f57ea62a.png)

**是 UEditor 的 BUG 还是组件的 BUG**
未测试

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: mac
 - 浏览器:  谷歌 latest
 - 组件版本:  v2.4.1
 - 是否使用了本仓库下载的 UEditor 资源文件:  是
 - 是否使用了我提供的 serverUrl:  否

**Comment by HaoChuan9421** [comment]
看你的使用姿势好像没啥问题，这里的参数我会透传到创建 editor 实例那里，你看一下 window.UEDITOR_CONFIG 里面有没有你的 autotypeset 设置。如果有的话，估计是 UEditor 的 BUG
