### ISSUE TITLE
编辑器样式不显示

### ISSUE THREAD

**Issue by ZhouLin323** [HaoChuan9421/vue-ueditor-wrap#104]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。
引入编辑器后，样式不显示
**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图
![微信图片_20200119141922](https://user-images.githubusercontent.com/20852408/72675953-b8684c00-3ac6-11ea-99bb-467a2ed962b6.png)

**开发环境**
 - 操作系统: [ Win10]
 - 浏览器:  [谷歌 76.0.3809.132 版本]
 - 组件版本:  [ v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [否]
 - 是否使用了我提供的 serverUrl:  [否]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
