### ISSUE TITLE
js压缩工具

### ISSUE THREAD

**Issue by tulongxCodes** [HaoChuan9421/vue-ueditor-wrap#105]
大佬用的什么压缩工具，我编译uedtor.all.js文件，压缩的时候总是报错。我是修改了一些源码的内容去掉了jsonp部分和初始化加载config.json部分。但是使用一些js压缩工具都报错。。

**Comment by HaoChuan9421** [comment]
UEditor 项目是通过 Grunt 打包的，参考一下官方的指南就好了 http://fex.baidu.com/ueditor/#dev-bale_width_grunt, 打包插架他们项目里都配置的有
