### ISSUE TITLE
ueditor上传图片后拖动图片自动添加style样式 手机端不能自适应问题

### ISSUE THREAD

**Issue by hankun8645** [HaoChuan9421/vue-ueditor-wrap#107]
ueditor上传图片后拖动图片自动添加style样式 手机端图片 不能自适应。

**Comment by HaoChuan9421** [comment]
vue-ueditor-wrap 只是一个“包装”了 UEditor 的 Vue 组件，组件本身并不是 UEditor 的 Vue 版，请不要将 UEditor 本身的 BUG 反馈到本仓库 ISSUE 中。
