### ISSUE TITLE
如何通过cdn引入'UEditor'

### ISSUE THREAD

**Issue by Percy6** [HaoChuan9421/vue-ueditor-wrap#109]
**你遇到了什么 BUG**
1.我将UEditor通过cdn的方式引入报错。

**如何复现**
复现 BUG 的步骤:
1. 将UEditor引入路径‘/static/UEditor/’改为cdn路径

**是 UEditor 的 BUG 还是组件的 BUG**
UEditor优化

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by HaoChuan9421** [comment]
那你至少要按顺序加载这两个文件，
![image](https://user-images.githubusercontent.com/5093611/76831793-f5e91b80-6862-11ea-87fd-bdc3ac60a24f.png)
而且要保证你CDN上的文件包含完整的UEditor代码哦！UEditor 会自动找他的一些依赖文件
![image](https://user-images.githubusercontent.com/5093611/76831656-b15d8000-6862-11ea-8442-c98cba70acc1.png)

**Comment by Percy6** [comment]
现在我是通过cdn引入的，ueditor.config.js和ueditor.all.js也正常加载了。但是现在出现一个新的问题，就是唤起'dialog'类似的操作报iframe跨域的错误(如：上传图片的dialog)。

**Comment by HaoChuan9421** [comment]
有两种方案你可以试一试:
一、 把一些类似上传图片的功能通过配置屏蔽掉，然后借助自定义按钮，自己实现一套上传图片的功能，这样还可以对接一些文件存储服务，比如阿里云的对象存储。
二、通过反向代理，把UEditor 相关的请求代理到 CDN 资源上，UEDITOR_HOME_URL 还是设置为 '/static/UEditor/'。下面是一个简单的 `Nginx` 配置。当访问 `/static/UEditor/` 路径下的文件时，如 `http://www.example.com/static/UEditor/ueditor.all.min.js` 就会映射到 `https://www.cdn.com/static/UEditor/ueditor.all.min.js` 。不过这只是一个简单的例子，提供一种思路，你根据你们公司项目的运维状况来决定。
```
server {
    listen       80;
    server_name www.example.com;

    location / {
        root   html;
        index  index.html index.htm;
    }

    location /static/UEditor/ {
        proxy_pass  https://www.cdn.com;
    }
}
```
实在不行，你去看一下 UEditor 的源码，找一下他们加载 iframe 的那段代码，然后改一改就中来。

**Comment by Percy6** [comment]
好的。非常谢谢😜



---原始邮件---
发件人: "郑昊川"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午4:44
收件人: "HaoChuan9421/vue-ueditor-wrap"<vue-ueditor-wrap@noreply.github.com&gt;;
抄送: "Percy6"<1421269362@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [HaoChuan9421/vue-ueditor-wrap] 如何通过cdn引入'UEditor' (#109)




 
有两种方案你可以试一试:
 一、 把一些类似上传图片的功能通过配置屏蔽掉，然后借助自定义按钮，自己实现一套上传图片的功能，这样还可以对接一些文件存储服务，比如阿里云的对象存储。
 二、通过反向代理，把UEditor 相关的请求代理到 CDN 资源上，UEDITOR_HOME_URL 还是设置为 '/static/UEditor/'。下面是一个简单的 Nginx 配置。当访问 /static/UEditor/ 路径下的文件时，如 http://www.example.com/static/UEditor/ueditor.all.min.js 就会映射到 https://www.cdn.com/static/UEditor/ueditor.all.min.js 。不过这只是一个简单的例子，提供一种思路，你根据你们公司项目的运维状况来决定。
 server {     listen       80;     server_name www.example.com;     location / {         root   html;         index  index.html index.htm;     }     location /static/UEditor/ {         proxy_pass  https://www.cdn.com;     } }  
实在不行，你去看一下 UEditor 的源码，找一下他们加载 iframe 的那段代码，然后改一改就中来。

**Comment by HaoChuan9421** [comment]
> 好的。非常谢谢😜

@Percy6  弄完之后可以把你的经验分享出来，避免后续的人踩坑

**Comment by Percy6** [comment]
好的😄



---原始邮件---
发件人: "郑昊川"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午4:51
收件人: "HaoChuan9421/vue-ueditor-wrap"<vue-ueditor-wrap@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Percy6"<1421269362@qq.com&gt;;
主题: Re: [HaoChuan9421/vue-ueditor-wrap] 如何通过cdn引入'UEditor' (#109)




  
好的。非常谢谢😜
  
@Percy6  弄完之后可以把你的经验分享出来，避免后续的人踩坑

**Comment by AaronConlon** [comment]
> 好的😄
> […](#)
> ---原始邮件--- 发件人: "郑昊川"<notifications@github.com&gt; 发送时间: 2020年3月17日(周二) 下午4:51 收件人: "HaoChuan9421/vue-ueditor-wrap"<vue-ueditor-wrap@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"Percy6"<1421269362@qq.com&gt;; 主题: Re: [HaoChuan9421/vue-ueditor-wrap] 如何通过cdn引入'UEditor' (#109) 好的。非常谢谢😜 @Percy6 弄完之后可以把你的经验分享出来，避免后续的人踩坑 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@Percy6 请问弄完了吗 😂 求分享
