### ISSUE TITLE
innerHtml报错

### ISSUE THREAD

**Issue by caiya** [HaoChuan9421/vue-ueditor-wrap#11]
我的vue页面每次首次加载ueditor显示正常，刷新页面后直接报错：
![](https://user-images.githubusercontent.com/12036572/42930146-ce2ab568-8b6e-11e8-9984-3405f599a65a.png)

**Comment by HaoChuan9421** [comment]
你这个是不是热加载保存自动刷新之后报的错？我之前好像也遇到过，但是手动刷新就没了，我刚才也没重现出来，所以不清楚你具体的报错时机是在什么，你可以描述的详细点吗，我们尝试一下一起解决

**Comment by caiya** [comment]
不是热加载保存报错，是页面首次加载后直接按F5刷新才报的错（或者点击浏览器刷新按钮），首次进入页面不会报错，如下是我的配置信息：
![image](https://user-images.githubusercontent.com/12036572/42979559-6dac2a18-8c05-11e8-89bd-05b5533d1ec6.png)
![image](https://user-images.githubusercontent.com/12036572/42979570-75b2bfec-8c05-11e8-8fcb-a73c792d42d3.png)
注：static下的UEditor是直接使用楼主在线demo下的，wrap包版本是最新的1.4.3

**Comment by HaoChuan9421** [comment]
看你的使用基本没问题。我看报错的地方是value监听出了问题，就是`v-model`语法糖监听的`step.content`出了问题。所以不知道你的`step.content`是不是`undefined`,我尝试给`UEditor`实例的`setContent`方法传一个`undefined`,会报错，和你的还不太一样，但是你可以排查一下是不是这个问题导致的，至于为什么刷新就会出现问题，我就不太理解了，你可以在开发模式下长按刷新按钮，强制刷新试一试
![image](https://user-images.githubusercontent.com/28668354/42980536-5ed2844c-8c0a-11e8-88db-7261c1822491.png)

![image](https://user-images.githubusercontent.com/28668354/42980445-e9c0b368-8c09-11e8-8ea4-f2b18c990dae.png)
