### ISSUE TITLE
删除编辑器中内容时，偶尔出现工具栏也被删除了

### ISSUE THREAD

**Issue by 1139221421** [HaoChuan9421/vue-ueditor-wrap#111]
版本是2.4.1

编辑好内容，然后ctrl+a 再delete删除所有，偶尔会出现ueditor的工具栏图标一起被删除了，
存在一定的偶然性，不是经常发生

vue + iview中使用

**Comment by JessciaVip** [comment]
我这里不是偶然，是必然。 当删除完编辑器中所有内容之后，该编辑器自动消失了，工具栏也消失了。我的配置是：
                   // 编辑器自动被内容撑高
                    autoHeightEnabled: true,
                    // 初始容器宽度
                    initialFrameWidth: '100%',
我发现只要autoHeightEnabled为 true, 就会出现这个问题。 而UEditor的官网例子（http://ueditor.baidu.com/website/examples/completeDemo.html）不会有这个问题存在。
不知道是不是插件本身的问题？
@HaoChuan9421  希望大佬能帮忙确认下。非常感谢。

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
