### ISSUE TITLE
IE出现无法正常输入的问题

### ISSUE THREAD

**Issue by xiaYong-web** [HaoChuan9421/vue-ueditor-wrap#116]
**你遇到了什么 BUG**
在IE浏览器中，出现输入文字出现错乱、无法删除、自动换行、无法输入的问题

**如何复现**
复现 BUG 的步骤:
![微信图片_20200514110707](https://user-images.githubusercontent.com/26805649/81888058-1f0ff900-95d3-11ea-818a-bfc4b11d89bc.png)

1.打开IE浏览器；
1. 进入http://ueditor.gitrr.com/#/。
3. 输入任何内容。
4. 出现报错。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  IE11 - 11.778.18362.0
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
DEMO可以复现问题：http://ueditor.gitrr.com/#/

**Comment by HaoChuan9421** [comment]
自动换行在 2.5.3 版本修复了，可以用 http://ueditor.gitrr.com/#/ 试一试
