### ISSUE TITLE
图片上传serverUrl时 会报http 请求失败

### ISSUE THREAD

**Issue by Ae86fast** [HaoChuan9421/vue-ueditor-wrap#117]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

大佬，使用你提供的serverUrl:  [e.g. http://35.201.165.105:8000/controller.php] 
在上传时候 会报未知的错误
![image](https://user-images.githubusercontent.com/30069358/82788899-ece87c00-9e9b-11ea-8e65-c8fbab8c9114.png)

后端给serverUrl是get的请求可以返回 json 但是 在 上传的时候会报500

**Comment by Ae86fast** [comment]
后端是java 的

**Comment by Ae86fast** [comment]
![image](https://user-images.githubusercontent.com/30069358/82973071-196dd680-a009-11ea-8a4b-21bfde6b0d20.png)
serverUrl 后端给的是get的请求 可以返回 一json 的数据
但是在 上传的图片就会报
![image](https://user-images.githubusercontent.com/30069358/82973190-5afe8180-a009-11ea-8f53-d75bb89fdabd.png)

**Comment by HaoChuan9421** [comment]
这是你们后端的问题
