### ISSUE TITLE
设置高度：initialFrameHeight: 32无效

### ISSUE THREAD

**Issue by 819slw** [HaoChuan9421/vue-ueditor-wrap#118]
设置initialFrameHeight: 32，渲染之后的高度并不是32.但是Ueditor本身是可以设置到32的

**Comment by HaoChuan9421** [comment]
vue-ueditor-wrap 只是一个“包装”了 UEditor 的 Vue 组件，组件本身并不是 UEditor 的 Vue 版，请不要将 UEditor 本身的 BUG 反馈到本仓库 ISSUE 中。
