### ISSUE TITLE
编辑器内图片获得焦点，要多次点击文本区域后才能让文本获得焦点

### ISSUE THREAD

**Issue by caze01** [HaoChuan9421/vue-ueditor-wrap#12]
RT

**Comment by HaoChuan9421** [comment]
😂观察的很细致，这个是UEditor的官方演示[Demo](http://ueditor.baidu.com/website/onlinedemo.html)。 也存在你说的问题，而且这个对使用感觉影响不大。所以我不打算修复

**Comment by shellus** [comment]
我也重现了这个问题，当选中图片，很难再输入文字，多点几次也很难点好。但是按一下esc就可以。
很严重的问题。

试了一下官方DEMO，确实是同一个问题。
那就不是这个封装能去解决的了。

**Comment by HaoChuan9421** [comment]
@shellus @caze01 百度编辑器一大堆BUG,官方都放弃了，我也只是看有没有影响使用比较严重的BUG,有的话就尝试修复一下

**Comment by caze01** [comment]
原因是出在图片的那个resize功能 项目对图片resize的功能不做要求 所以我简单粗暴的把它禁了




| |
潘才捷
邮箱：pcj1125@126.com
|

签名由 网易邮箱大师 定制

在2018年08月14日 17:12，郑昊川 写道：

@shellus@caze01 百度编辑器一大堆BUG,官方都放弃了，我也只是看有没有影响使用比较严重的BUG,有的话就尝试修复一下

**Comment by HaoChuan9421** [comment]
@caze01 那就行

**Comment by zerozyn** [comment]
> 原因是出在图片的那个resize功能 项目对图片resize的功能不做要求 所以我简单粗暴的把它禁了 | | 潘才捷 邮箱：pcj1125@126.com | 签名由 网易邮箱大师 定制 在2018年08月14日 17:12，郑昊川 写道： @shellus@caze01 百度编辑器一大堆BUG,官方都放弃了，我也只是看有没有影响使用比较严重的BUG,有的话就尝试修复一下 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

你好，遇到了跟你一样的问题，可以说下在哪改吗?
谢谢
