### ISSUE TITLE
草稿功能有缺陷

### ISSUE THREAD

**Issue by suguoyao** [HaoChuan9421/vue-ueditor-wrap#125]
**你遇到了什么 BUG**
开启enableAutoSave自动保存后，内容会存入localstorage，但刷新页面后点击恢复草稿无效。

**如何复现**
复现 BUG 的步骤:
1. 输入内容，自动保存
2. 刷新页面
3. 点击“从草稿箱加载”按钮，无效

**是 UEditor 的 BUG 还是组件的 BUG**
看了下源码是组件的bug，每次实例化时都会动态生成父容器的editorId，草稿对应的缓存key也和id挂钩，所以导致刷新页面重新加载编辑器时，id已经无法对应上了。
```js
this.id = 'editor_' + Math.random().toString(16).slice(-6)
```

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
无

**开发环境**
 - 操作系统: MacOS
 - 浏览器:  谷歌 83.0.4103.116（正式版本） （64 位）
 - 组件版本:  2.4.3
 - 是否使用了本仓库下载的 UEditor 资源文件:  是
 - 是否使用了我提供的 serverUrl:  否

**Comment by suguoyao** [comment]
已自己重写组件解决

将
```js
_initEditor() {
     // 这么做是为了支持 Vue SSR，因为如果把 id 属性放在 data 里会导致服务端和客户端分别计算该属性的值，而造成 id 
不匹配无法初始化的 BUG
    this.$refs.script.id = this.id = 'editor_' + Math.random().toString(16).slice(-6)
...
```

改为接收一个自定义editorId的prop
```js
...
props: {
    editorId: {
        type: String,
        default: 'editor_' + Math.random().toString(16).slice(-6)
     }
},
...
_initEditor() {
    this.$refs.script.id = this.id = this.editorId
...
```

**Comment by HaoChuan9421** [comment]
谢谢你的反馈，确实存在这个问题哈，安装最新版本组件并手动设置 editorId 属性就可以了。
 ```html
<vue-ueditor-wrap v-model="msg" editor-id="sometext" ></vue-ueditor-wrap>
```
如果你的项目是服务端渲染的就不要按照你上面的那种方式改哈，会导致编辑器无法初始化的，如果不是就没太大关系，你可以看一下我最新的[提交记录](https://github.com/HaoChuan9421/vue-ueditor-wrap/commit/ba51d9e61aba64b57be738b0f3e17b818becc164#diff-eba3ed6f45b8c0ab83370bccf313c64a)。

**Comment by suguoyao** [comment]
@HaoChuan9421 谢谢~
