### ISSUE TITLE
如何自定义上传功能?(阿里云,腾讯云等上传功能)

### ISSUE THREAD

**Issue by phoock** [HaoChuan9421/vue-ueditor-wrap#126]
公司采用腾讯云储存来做存储功能,之前用wangeditor编辑器,通过函数customUploadImg来自定义上传.
可是产品又习惯于ueditor编辑器...在苦逼的集成过程中来到此处,请问大佬我该如何自定上传?

**Comment by HaoChuan9421** [comment]
参考常见问题6
