### ISSUE TITLE
文本内容中包含>或<时，getPlainTxt()返回的内容是 &lt;或&gt;

### ISSUE THREAD

**Issue by dongwenting** [HaoChuan9421/vue-ueditor-wrap#132]
希望返回原生的符号

**Comment by HaoChuan9421** [comment]
vue-ueditor-wrap 只是一个“包装”了 UEditor 的 Vue 组件，组件本身并不是 UEditor 的 Vue 版，请不要将 UEditor 本身的 BUG 反馈到本仓库 ISSUE 中。
