### ISSUE TITLE
vue-ueditor-wrap.min.js?6625:1 加载ueditor.config.js失败,请检查您的配置地址UEDITOR_HOME_URL填写是否正确!

### ISSUE THREAD

**Issue by beevivo6** [HaoChuan9421/vue-ueditor-wrap#133]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by beevivo6** [comment]
为啥，老配得不对

**Comment by beevivo6** [comment]
config: {
        // 编辑器不自动被内容撑高
        autoHeightEnabled: false,
        // 初始容器高度
        initialFrameHeight: 240,
        // 初始容器宽度
        initialFrameWidth: "100%",
        // 上传文件接口（这个地址是我为了方便各位体验文件上传功能搭建的临时接口，请勿在生产环境使用！！！）
        serverUrl: "http://35.201.165.105:8000/controller.php",
        // UEditor 资源文件的存放路径，如果你使用的是 vue-cli 生成的项目，通常不需要设置该选项，vue-ueditor-wrap 会自动处理常见的情况，如果需要特殊配置，参考下方的常见问题2
        UEDITOR_HOME_URL: "/static/UEditor/",
        // 配合最新编译的资源文件，你可以实现添加自定义Request Headers,详情https://github.com/HaoChuan9421/ueditor/commits/dev-1.4.3.3
        // headers: {
        //   access_token: '37e7c9e3fda54cca94b8c88a4b5ddbf3'
        // }
      },

**Comment by beevivo6** [comment]
为什么呢？总是提示  vue-ueditor-wrap.min.js?6625:1 加载ueditor.config.js失败,请检查您的配置地址UEDITOR_HOME_URL填写是否正确!？
config: {
        // 编辑器不自动被内容撑高
        autoHeightEnabled: false,
        // 初始容器高度
        initialFrameHeight: 240,
        // 初始容器宽度
        initialFrameWidth: "100%",
        // 上传文件接口（这个地址是我为了方便各位体验文件上传功能搭建的临时接口，请勿在生产环境使用！！！）
        serverUrl: "http://35.201.165.105:8000/controller.php",
        // UEditor 资源文件的存放路径，如果你使用的是 vue-cli 生成的项目，通常不需要设置该选项，vue-ueditor-wrap 会自动处理常见的情况，如果需要特殊配置，参考下方的常见问题2
        UEDITOR_HOME_URL: "/static/UEditor/",
        // 配合最新编译的资源文件，你可以实现添加自定义Request Headers,详情https://github.com/HaoChuan9421/ueditor/commits/dev-1.4.3.3
        // headers: {
        //   access_token: '37e7c9e3fda54cca94b8c88a4b5ddbf3'
        // }
      },

**Comment by beevivo6** [comment]
![image](https://user-images.githubusercontent.com/29418930/91159522-c33d2c00-e6fa-11ea-9de6-d29a1bb22cd2.png)

**Comment by weitingGao** [comment]
我也遇到相同的错误，路径是正确的，但是报错找不到

**Comment by Nosaj0620** [comment]
我也遇到这个问题了   之前还可以的

**Comment by HaoChuan9421** [comment]
参考常见问题2
