### ISSUE TITLE
切换html后，contentChange不会再触发了，v-model也失效了

### ISSUE THREAD

**Issue by dbz5489** [HaoChuan9421/vue-ueditor-wrap#136]
如题，请问怎么获得切换Html源码模式的数据呢

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
