### ISSUE TITLE
IE 浏览器 仿真ie10 编辑器不显示

### ISSUE THREAD

**Issue by fanlina157** [HaoChuan9421/vue-ueditor-wrap#137]
![image](https://user-images.githubusercontent.com/40651839/93412279-713d8f80-f8cf-11ea-9bdd-010d95eae960.png)

**Comment by HaoChuan9421** [comment]
2.5.3 版本修复了，亲测 IE10 已经可以了，可以用 http://ueditor.gitrr.com/#/ 试一试
