### ISSUE TITLE
图片上传成功后，富文本框中不显示图片

### ISSUE THREAD

**Issue by Yongest** [HaoChuan9421/vue-ueditor-wrap#138]
**图片上传成功后，富文本框中不显示图片**

**Comment by Yongest** [comment]
![Uploading 微信图片_20200917161316.png…]()

**Comment by Yongest** [comment]
[](http://120.79.206.175/1316.png)

**Comment by Yongest** [comment]
![image](http://120.79.206.175/1316.png)

**Comment by Yongest** [comment]
我特么的图片都不给上传了么

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
