### ISSUE TITLE
自动排版

### ISSUE THREAD

**Issue by huanghujie18** [HaoChuan9421/vue-ueditor-wrap#140]
**你遇到了什么 BUG**
如果复制了一篇文章 ，p标签含有固定宽度  点击自动排版  p标签的内容不会扩展到编辑器的宽度
![e3b722d8ea86d868ad7887c9c48df05](https://user-images.githubusercontent.com/71969527/94540798-78727f00-0279-11eb-9ede-14b585de0735.png)

简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**Comment by HaoChuan9421** [comment]
vue-ueditor-wrap 只是一个“包装”了 UEditor 的 Vue 组件，组件本身并不是 UEditor 的 Vue 版，请不要将 UEditor 本身的 BUG 反馈到本仓库 ISSUE 中。
