### ISSUE TITLE
html输入后自动添加了P标签，原有div标签也切换成了p标签，带的style样式不见了

### ISSUE THREAD

**Issue by 1369220324** [HaoChuan9421/vue-ueditor-wrap#141]
<div style="margin:10px 15px 0px 15px;">
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:justify;">
			您好！
		</p>
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:justify;text-indent: 2em;">
			按照市委巡视工作部署，市委巡视九组自即日起，对你单位开展巡视。
		</p>	
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:justify;text-indent: 2em;">
			为坚持“发现问题、形成震慑、推动改革、促进发展”的巡视工作方针，广泛收集意见建议，聚焦重点问题、重点人员，我们设计了本套电子问卷调查系统。请在相关选项后，选择存在问题的重点人员、重点部门，并用简明的文字填写重点事例内容。
		</p>
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:justify;text-indent: 2em;">
			为保护提供线索及反映问题的人员信息，此问卷系统采取不记名方式，并对内容做加密处理，请放心填写。
		</p>
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:justify;text-indent: 2em;">
			请您本着对党忠诚、对事业发展负责的态度，客观公正填写问卷，实事求是反映问题。
		</p>
		<br/>
		<br/>
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:right">
			市委巡视九组
		</p>
		<p style="font-family: 微软雅黑; color: rgb(51, 51, 51); letter-spacing: 0px; font-size: 20px;text-align:right">
			2020年8月
		</p>
	</div>

这段代码贴进去，出来就变了

**Comment by 1369220324** [comment]
html输入后自动添加了P标签，原有div标签也切换成了p标签，带的style样式不见了

**Comment by HaoChuan9421** [comment]
看一下 ueditor.config.js，试一试 allowDivTransToP 参数
