### ISSUE TITLE
Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by caitoucom** [HaoChuan9421/vue-ueditor-wrap#143]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
按流程将vue-ueditor-wrap配置到项目中 出现Cannot read property '_c' of undefined

**是 UEditor 的 BUG 还是组件的 BUG**
不确定

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
![1606185071(1)](https://user-images.githubusercontent.com/39787855/100039488-4d9f4400-2e40-11eb-9709-f0ac06dd31bf.jpg)

**开发环境**
 - 操作系统: [Win10]
 - 浏览器:  [谷歌 87.0.4280.66（正式版本）]
 - 组件版本:  [ v2.4.4]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [是]
 - 是否使用了我提供的 serverUrl:  [无]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by caitoucom** [comment]
vue 3x

**Comment by fcsh820** [comment]
![image](https://user-images.githubusercontent.com/6018384/100848840-a748e380-34bc-11eb-9f4c-d42812573484.png)
遇到相同的问题，使用vue3.0

**Comment by zkQAQ** [comment]
同问 相同的问题 用的vue 3.0

**Comment by HaoChuan9421** [comment]
哈哈，不好意思，姗姗来迟了，组件的 3.x 版本已经发布了，支持 Vue3，可以参考这里 https://haochuan9421.github.io/vue-ueditor-wrap/#/home
