### ISSUE TITLE
如何调用 uparse 方法，对生成的html代码，进行解析 

### ISSUE THREAD

**Issue by stt04521** [HaoChuan9421/vue-ueditor-wrap#144]
uparse 方法怎么调用呢？

**Comment by HaoChuan9421** [comment]
在 ready 之后拿到 editor 实例，通过实例调用就可以了

**Comment by HaoChuan9421** [comment]
按照 UEditor 的文档该怎么用就怎么用呀，http://fex.baidu.com/ueditor/#start-uparse
