### ISSUE TITLE
多图上传过程中，上传了超过2张以上的图片的时候，图片没法正常上传上去

### ISSUE THREAD

**Issue by kizunaY** [HaoChuan9421/vue-ueditor-wrap#146]
多图上传过程中，上传了超过2张以上的图片的时候，图片没法正常上传上去

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
