### ISSUE TITLE
请问现在有安排使UEditor 支持vue.js  3.0版本的计划吗？

### ISSUE THREAD

**Issue by zkQAQ** [HaoChuan9421/vue-ueditor-wrap#147]
请问现在有安排使UEditor 支持vue.js 3.0版本的计划吗

**Comment by HaoChuan9421** [comment]
组件的 3.x 版本已经发布了，支持 Vue3，可以参考这里 https://haochuan9421.github.io/vue-ueditor-wrap/#/home
