### ISSUE TITLE
自定义按钮又是会显示不出来 vue项目

### ISSUE THREAD

**Issue by MrYangZC** [HaoChuan9421/vue-ueditor-wrap#152]
自定义按钮又是会显示不出来 vue项目

代码采用 FAQ 第四条
![image](https://user-images.githubusercontent.com/29966789/112279343-ca431180-8cbe-11eb-8d24-4df4b6a5003b.png)

**截图**
如果可能，提供截图
![image](https://user-images.githubusercontent.com/29966789/112278848-396c3600-8cbe-11eb-8627-0a7a91d597ac.png)

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌  87.0.4280.88 版本]
 - 组件版本:  [e.g. v2.4.4]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]

**Comment by HaoChuan9421** [comment]
会不会是网速慢，图片没加载出来呀😂，如果不是的话，提供一个能复现问题的在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)

**Comment by MrYangZC** [comment]
https://codesandbox.io/s/vue-ueditor-wrap-v2-demo-forked-5tncv

**Comment by MrYangZC** [comment]
> 会不会是网速慢，图片没加载出来呀😂，如果不是的话，提供一个能复现问题的在线 Demo 或 GitHub 仓库。
> 
> [在线 Demo 模版](https://codesandbox.io/s/uestq)
> [GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)

https://codesandbox.io/s/vue-ueditor-wrap-v2-demo-forked-5tncv

**Comment by MrYangZC** [comment]
不好意思！之前有点忙，这个是demo 地址：https://codesandbox.io/s/vue-ueditor-wrap-v2-demo-forked-5tncv  
在2021年4月6日 ***@***.***> 写道：

会不会是网速慢，图片没加载出来呀😂，如果不是的话，提供一个能复现问题的在线 Demo 或 GitHub 仓库。

在线 Demo 模版
GitHub 仓库模版

**Comment by HaoChuan9421** [comment]
> 不好意思！之前有点忙，这个是demo 地址：https://codesandbox.io/s/vue-ueditor-wrap-v2-demo-forked-5tncv 在2021年4月6日 ***@***.***> 写道： 会不会是网速慢，图片没加载出来呀😂，如果不是的话，提供一个能复现问题的在线 Demo 或 GitHub 仓库。 在线 Demo 模版 GitHub 仓库模版 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，我看看

**Comment by HaoChuan9421** [comment]
我看线上是一个组件有按钮，一个没按钮，这是因为注册的 UI 重名了，不知道你说的"时有时无"是不是这个问题导致的
![image](https://user-images.githubusercontent.com/5093611/114965476-3a4e4d00-9ea3-11eb-980f-3b8e60a25275.png)

![image](https://user-images.githubusercontent.com/5093611/114965738-c3fe1a80-9ea3-11eb-80be-cdf8972785f2.png)

**Comment by MrYangZC** [comment]
应该是 UI 重名了，我是for循环的 没有注意这个问题,多谢！


在2021年4月16日 ***@***.***> 写道：

我看线上是一个组件有按钮，一个没按钮，这是因为注册的 UI 重名了，不知道你说的"时有时无"是不是这个问题导致的
