### ISSUE TITLE
有序列表和无序列表缺失自定义部分的图标

### ISSUE THREAD

**Issue by 2265886429** [HaoChuan9421/vue-ueditor-wrap#155]
<img width="725" alt="ueditor" src="https://user-images.githubusercontent.com/8945527/113847957-8fff6700-97ca-11eb-893a-6709ccfad6e0.png">

**Comment by HaoChuan9421** [comment]
这些特殊的列表序号其实是一些小图片，UEditor 默认的图片地址 http://bs.baidu.com/listicon/ 已经 404 了，所以看不见这些序号。我已经把这些图片另存下来了，可以点[这里](https://ueditor-1302968899.cos.ap-guangzhou.myqcloud.com/zip/listicon.zip)下载。
1. 把这图片保存到下列位置：
![image](https://user-images.githubusercontent.com/5093611/113873198-2c376700-97e7-11eb-91f8-56b5332f9505.png)
2. 设置 config 中的 `listiconpath: UEDITOR_HOME_URL + "listicon/"`

这样编辑的时候就可以看到序号了。

但要注意的一点的是，在还原编辑器内容时，要使用 `ueditor.parse.js`，不然还原后的富文本还是看不到序号的。可以参考 UEditor 官方关于 [编辑内容展示](http://fex.baidu.com/ueditor/#start-uparse)的文档 和我写的[编辑内容展示](https://haochuan9421.github.io/vue-ueditor-wrap/#/uparse) 的示例。

还有一点就是 `ueditor.parse.js` 和 `ueditor.parse.min.js`  本身是有一个小 BUG 的，看下图修改一下就好了
![image](https://user-images.githubusercontent.com/5093611/113874216-242bf700-97e8-11eb-92d6-1ff68f6d9324.png)

如果不使用 `ueditor.parse.js` 来还原，可以手动设置样式，附上一段 `less` 代码：
```less
.list(@i) when (@i > -1) {
  .list((@i - 1));
  .list-cn-1-@{i} {
    // 注意这里的路径，根据小图片的位置进行调整
    background-image: url('/UEditor/listicon/list-cn-1-@{i}.gif');
  }
  .list-cn-2-@{i} {
    background-image: url('/UEditor/listicon/list-cn-2-@{i}.gif');
  }
  .list-cn-3-@{i} {
    background-image: url('/UEditor/listicon/list-cn-3-@{i}.gif');
  }

  .list-num-1-@{i} {
    background-image: url('/UEditor/listicon/list-num-1-@{i}.gif');
  }
  .list-num-2-@{i} {
    background-image: url('/UEditor/listicon/list-num-2-@{i}.gif');
  }
  .list-num-3-@{i} {
    background-image: url('/UEditor/listicon/list-num-3-@{i}.gif');
  }
}
.list(99);
```

**Comment by beck126** [comment]
图片没办法下载啊
