### ISSUE TITLE
alert警告

### ISSUE THREAD

**Issue by woyehaizaixiang** [HaoChuan9421/vue-ueditor-wrap#156]
检测测试环境是什么意思，

**Comment by HaoChuan9421** [comment]
有些小伙伴可能会看到这样的告警：
![image](https://user-images.githubusercontent.com/5093611/114503163-7002f400-9c5f-11eb-9382-057453497bc3.png)

UEditor 作为一款富文本编辑器，包含图片上传、视频上传、远程图片抓取等功能。这需要部署对应的后端服务，才能正常使用。

正确部署后的 UEditor 服务，一般会提供一个统一的 HTTP 请求接口，前端同学只需要把他配置到 UEDITOR_CONFIG.serverUrl 中即可。

文档里提供了一个测试的 serverUrl http://35.201.165.105:8000/controller.php 或 https://ueditor.szcloudplus.com/cos ,后台日志显示访问量很大，已经吃掉了我服务器很多费用😂，这个接口是我个人搭建的，初衷是为了方便各位小伙伴看文档或开发时能更好的体验百度编辑器的完整功能，完全是出于帮助他人的初衷且免费的。

![image](https://user-images.githubusercontent.com/5093611/114504628-beb18d80-9c61-11eb-95da-ce0a9ca178fc.png)

由于我设置了允许跨域访问，发现有**很多人在线上环境白嫖我的接口**😡😡😡，这不仅对我造成了额外的经济负担，也占用其他同学的资源！所以对疑似线上环境的调用进行了告警，此前文档也三番五次强调这个 serverUrl 仅供测试使用，不可用于生产环境！
![image](https://user-images.githubusercontent.com/5093611/114503578-24047f00-9c60-11eb-875a-5e6bc84527a6.png)
![image](https://user-images.githubusercontent.com/5093611/114503628-3383c800-9c60-11eb-8dfc-9c2e398abcb0.png)

为了更好的防止此类事情发生，现同一 IP 最多只能调用一百次，超过后自动加入黑名单，这个次数对于体验 serverUrl 的功能已经足够了。

对于需要使用上传图片等功能的同学，UEditor 官方已经提供了 PHP、ASP、ASP.NET、JSP 的[部署说明](http://fex.baidu.com/ueditor/#server-deploy)，我也提供一个 [Node 的示例代码](https://github.com/HaoChuan9421/ueditor-koa-server)，事实上我提供了那个 serverUrl 就是 Node 写的。再次强调：**拒绝白嫖！！！自己动手，丰衣足食！**

**Comment by HaoChuan9421** [comment]
**白嫖数量惊人**，加了告警之后，一天时间就有十几个人加微信反馈！！！
![image](https://user-images.githubusercontent.com/5093611/114506652-aee77880-9c64-11eb-91c9-815ea57320f0.png)

**Comment by woyehaizaixiang** [comment]
已将serverUrl设置为空关闭alert警告，上传文件、图片等功能通过oss实现了

**Comment by woyehaizaixiang** [comment]
已将serverUrl设置为空关闭alert警告，上传文件、图片等功能通过oss实现了

**Comment by xyip** [comment]
大佬  请问你的跨域问题怎么处理的  我这边遇到跨域问题

Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute

**Comment by HaoChuan9421** [comment]
> 大佬 请问你的跨域问题怎么处理的 我这边遇到跨域问题
> 
> Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute

你这个跨域请求设置了第三方Cookie，之前我写过一篇相关的博客，你可以了解一下 https://juejin.cn/post/6963632513914765320

**Comment by Lny-nice** [comment]
工具栏很多工具失效咋回事啊

**Comment by cjh-store** [comment]
> 已将serverUrl设置为空关闭alert警告，上传文件、图片等功能通过oss实现了

是否有代码示例看看怎么实现的呢 遇到相同需求

**Comment by woyehaizaixiang** [comment]
> 
可以参考这个，主要是24540行代码
https://github.com/woyehaizaixiang/vue-ueditor/blob/master/ueditor.all.min.js

**Comment by woyehaizaixiang** [comment]
可以参考这个，主要是24540行代码开始
https://github.com/woyehaizaixiang/vue-ueditor/blob/master/ueditor.all.min.js

**Comment by woyehaizaixiang** [comment]
> > 已将serverUrl设置为空关闭alert警告，上传文件、图片等功能通过oss实现了
> 
> 是否有代码示例看看怎么实现的呢 遇到相同需求

可以参考这个，主要是24540行代码开始
https://github.com/woyehaizaixiang/vue-ueditor/blob/master/ueditor.all.min.js
