### ISSUE TITLE
最新版打字光标会跳到顶行

### ISSUE THREAD

**Issue by chenjun-110** [HaoChuan9421/vue-ueditor-wrap#157]
反馈问题请遵循下列要求，否则直接关闭：

1. vue-ueditor-wrap 只是一个“包装”了 UEditor 的 Vue 组件，组件本身并不是 UEditor 的 Vue 版，请不要将 UEditor 本身的 BUG 反馈到本仓库 ISSUE 中。
2. 请了解[提问的艺术](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)，清晰的描述出你的问题。
3. 提供可复现问题的在线 Demo 或 GitHub 仓库，在能复现问题的前提下保证最小代码量，不要把你的一整个项目发过来。

在线 Demo 模版 [v3 版本](https://codesandbox.io/s/gqc5m)
在线 Demo 模版 [v2 版本](https://codesandbox.io/s/uestq)
GitHub 仓库模版 [v3 版本](https://github.com/HaoChuan9421/vue-ueditor-wrap-v3-demo)
GitHub 仓库模版 [v2 版本](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)

**Comment by chenjun-110** [comment]
换2.4.4没问题

**Comment by chenjun-110** [comment]
目测是v-modal的值变化导致的。

**Comment by HaoChuan9421** [comment]
我试了一下没有这个问题呀，能说一下你是什么环境吗？操作系统，浏览器，浏览器版本？
