### ISSUE TITLE
重复渲染

### ISSUE THREAD

**Issue by penjay** [HaoChuan9421/vue-ueditor-wrap#159]
在单页应用中，开启了keepalive的情况下，会重复渲染2个编辑器，如图：
![image](https://user-images.githubusercontent.com/23008915/119234706-d8e46280-bb61-11eb-984e-22e764856f0d.png)
![image](https://user-images.githubusercontent.com/23008915/119234714-dda91680-bb61-11eb-9131-6a6c5cec43b6.png)

**Comment by HaoChuan9421** [comment]
我试了一下，keep-alive 并不会出现你说的渲染两个编辑器的问题，你参考一下这个 [Demo](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo/tree/issue/159)。
![image](https://user-images.githubusercontent.com/5093611/119249050-52af3700-bbc8-11eb-846e-ea3a5c75274f.png)

如果 Demo 和你的场景不一致的话， fork 一个这个 Demo，提供一个能复现问题的版本

**Comment by penjay** [comment]
好像又不是keep-alive的问题，但不知道是哪里的问题。
我有2个项目，其中一个A没有任何问题，单页应用(keep-alive)切换后都是正常的。
但是我提问的这个项目B，只要切换tab，就会一直渲染UE，console看到每次切换都会新增editor_xxxxx。

今天我复制了没有问题的那个A，把views全删了，把B的views复制进去，又没有任何问题了。。。。。。

so，，我解决了，但是我不知道是什么问题，谢谢您的回答。

**Comment by zhujujun** [comment]
我也出现了这个问题  版本2.5.3 偶发性出现的 一个vue-ueditor-wrap组件渲染了二次 估计是watch value那里判断问题

**Comment by HaoChuan9421** [comment]
> 我也出现了这个问题 版本2.5.3 偶发性出现的 一个vue-ueditor-wrap组件渲染了二次 估计是watch value那里判断问题

有没有啥规律能稳定复现一下？

**Comment by zhujujun** [comment]
这个不容易重现 特定的环境:gch下一些浏览器上传出现 昨天我跟你发的demo对比了下 我这边在组件上没加editorId属性用的随机的 估计是这个原因 现在是用的固定的id 没有出现2个文本编辑器了 但是我估计div还是渲染了2次现在出现一个编辑器相当解决了。 
本质是一个vue-ueditor-wrap组件实例调用了2次initueditor方法 这个应该不知道怎么解决

**Comment by momu-2016** [comment]
我也出现了一样的问题，从列表进去编辑，就是两个，刷新一下页面，就只剩一个了

**Comment by HaoChuan9421** [comment]
安装一下最新版的试一试 2.5.4

**Comment by keminu** [comment]
我也出现了同样的问题，版本2.4.1，偶尔会出现

**Comment by keminu** [comment]
> 我也出现了同样的问题，版本2.4.1，偶尔会出现

使用最新版本2.5.6 问题没有了

**Comment by zhujujun** [comment]
我这边又重现了2.5.6 刷新浏览出现2个富文本

- [ ] **
![20A5CFB9-9D0C-44b4-B49E-C4CC7B34DDE8](https://user-images.githubusercontent.com/26269320/126746872-22fd2127-f3ed-4445-88cc-11ef12e5adf7.png)
**
