### ISSUE TITLE
vue3.0 报错Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by tianlang89757** [HaoChuan9421/vue-ueditor-wrap#162]
组件内注册使用时报错：
![image](https://user-images.githubusercontent.com/11829897/132152194-2a485a18-c1a6-4fdf-9184-7aa5033a34c5.png)

![image](https://user-images.githubusercontent.com/11829897/132152604-9ad8a0d4-eaf0-46a2-b6d9-19b268da2698.png)

![image](https://user-images.githubusercontent.com/11829897/132152647-54d55b4e-b96f-4f48-ae7b-dcaf06cc8313.png)
麻烦老师指导解决一下问题

**Comment by HaoChuan9421** [comment]
你这个是2.x的写法，如果是 Vue3 的话，这样写：
```js
import { VueUeditorWrap } from "vue-ueditor-wrap";
```
 或
 ```js
 // main.js
import { createApp } from 'vue';
import VueUeditorWrap from 'vue-ueditor-wrap';
import App from './App.vue';

createApp(App).use(VueUeditorWrap).mount('#app');
 ```

**Comment by tianlang89757** [comment]
好的，谢谢老师
