### ISSUE TITLE
遇到一个问题，请教下你

### ISSUE THREAD

**Issue by amwihtfei** [HaoChuan9421/vue-ueditor-wrap#17]
背景：我的1个组件中存在多个ueditor，我再mounted里面执行ajax请求加载数据并返回成功
问题：只显示第1个ueditor里面的内容；这个时候其它ueditor还没有加载完全；等加载完全后仅仅第一个ueditor里面显示内容
我的尝试：update中进行ajax请求，这个时候所有的ueditor会显示内容；但是没有办法正常的修改保存
需要：初始化一次性所有的ueditor显示对应的内容

**Comment by HaoChuan9421** [comment]
`<vue-ueditor-wrap @ready="ready"  ></vue-ueditor-wrap>`
在ready之后调用接口
