### ISSUE TITLE
首次加载编辑器提示"Cannot read property 'innerHTML' of undefined",刷新后编辑器内才有内容

### ISSUE THREAD

**Issue by wuyangjiacuo** [HaoChuan9421/vue-ueditor-wrap#19]
![mgle6 1dyzm4q1wbg ob_g](https://user-images.githubusercontent.com/21200419/45478403-70b90e00-b776-11e8-8774-341dd420fa88.png)
![image](https://user-images.githubusercontent.com/21200419/45478540-c2619880-b776-11e8-803d-23ef2c2a0b8c.png)

ajax获取数据是放在@ready里面的
事情就是这样的,点页面进来为编辑器赋值内容,但是报错呢
刷新就又有了

**Comment by HaoChuan9421** [comment]
可否给data里的`info`和组件使用的地方截个图？

**Comment by wuyangjiacuo** [comment]
![image](https://user-images.githubusercontent.com/21200419/45478859-7fec8b80-b777-11e8-979e-18a0f4b8e454.png)

**Comment by HaoChuan9421** [comment]
这么看是没什么问题😂，你安装的1.4.0版本吗？

**Comment by wuyangjiacuo** [comment]
最新版本的ueditor呢😂

**Comment by HaoChuan9421** [comment]
我的意思是你`vue-ueditor-wrap`是不是1.4.0，百度编辑器BUG也很多，你的资源文件是不是我[dist](https://github.com/HaoChuan9421/vue-ueditor-wrap/tree/master/dist)目录下下载的？我从你代码看问题不大

**Comment by wuyangjiacuo** [comment]
好像不是哦,哈哈,明白了老铁
