### ISSUE TITLE
需要添加插件如何使用

### ISSUE THREAD

**Issue by wwenj** [HaoChuan9421/vue-ueditor-wrap#20]
需要添加UEditor公式插件
https://ueditor.baidu.com/website/kityformula.html

**Comment by HaoChuan9421** [comment]
第一步：`npm i vue-ueditor-wrap@1.4.1`（新增了name属性，方便公式插件的表单提交）
第二步： 我单独为公式插件建了一个[demo分支](https://github.com/HaoChuan9421/vue-ueditor-wrap-demo/tree/formula),你克隆下来，看一看
第三步：`npm run dev`执行,为了测试提交表单的效果，我还写了一个`node`的`post`接口，你进入`server`目录下,执行`node index.js`，这个接口就起来了，地址是`localhost:3000/ueditor`，你可以提交一下公式的表单，试试效果，实际开发中，如果需要提交到后端，你需要使用你们自己的服务器接口。

如果还有问题，欢迎随时交流
