### ISSUE TITLE
配置文件总是错误

### ISSUE THREAD

**Issue by ygp1026** [HaoChuan9421/vue-ueditor-wrap#21]
![image](https://user-images.githubusercontent.com/13300966/46732698-cc68af80-ccc0-11e8-99b1-bb8c34068d26.png)
![image](https://user-images.githubusercontent.com/13300966/46732718-ddb1bc00-ccc0-11e8-9232-c8ee8638e470.png)
不知道哪里导致的配置文件错误，导致图片上传不可用

**Comment by HaoChuan9421** [comment]
你配置正确的`serverUrl `了吗

**Comment by HaoChuan9421** [comment]
你们后端给你的地址有问题，上面的提示文字已经说的很清楚了

**Comment by ygp1026** [comment]
我后台返回的是jsoup数据格式，也就是跨域的数据
直接用了config.json的数据返回，不知道要如何配置

**Comment by HaoChuan9421** [comment]
请求配置文件就是jsoup的，但是你实际上传的图片文件是走ajax请求的，如果你没有配置代理就需要后端开放CORS，就是说你使用那个接口上传图片，会看到类似`access-control-allow-origin: *`这样的响应头

**Comment by ygp1026** [comment]
我特意配置了一个错误的路径，后台配置错误控制台会有错误
如果配置正确则不会有上面的错误
![image](https://user-images.githubusercontent.com/13300966/46734366-8b26ce80-ccc5-11e8-953b-d39bce66191b.png)

目前我仅针对配置的请求返回jsoup，其他的是返回正常的json
图片上传这个显示不可使用的时候还没有请求后台吧，


![image](https://user-images.githubusercontent.com/13300966/46734540-1f913100-ccc6-11e8-88e1-4b9364c4950b.png)

**Comment by HaoChuan9421** [comment]
我只想知道你后端有没有配置CORS？

**Comment by ygp1026** [comment]
![image](https://user-images.githubusercontent.com/13300966/46734752-c544a000-ccc6-11e8-99c8-2a46c925f1d5.png)

**Comment by HaoChuan9421** [comment]
你把我的demo克隆下来，然后把里面的`serverUrl `字段换成你的，看能不能上传

**Comment by ygp1026** [comment]
![image](https://user-images.githubusercontent.com/13300966/46735251-43ee0d00-ccc8-11e8-867d-9fff49eff8e9.png)
好像也不可以

**Comment by HaoChuan9421** [comment]
那就是你的问题了，你再好好检查吧，崔莹

**Comment by ygp1026** [comment]
OK，谢谢

**Comment by HaoChuan9421** [comment]
那很可能就是你的问题的了，那个demo还是比较稳定的
