### ISSUE TITLE
有弹层的按钮，切换路由。弹层不消失

### ISSUE THREAD

**Issue by xjccc** [HaoChuan9421/vue-ueditor-wrap#22]
请问，我切换页面的时候如何销毁呢。。

**Comment by HaoChuan9421** [comment]
不太清楚你的表述？

**Comment by xjccc** [comment]
就是我现在页面创建了这个富文本，然后点击那个换背景的按钮，出现一个弹层，这个时候返回上一页。这个弹层还在。。还有就是我怎么单图上传。。需要怎么配置一下。。

**Comment by HaoChuan9421** [comment]
你可以调用实例的destory方法，这个会把富文本变成textarea，然后你可以通过DOM操作把它移除，关于如何单图上传，你可以借助自定义按钮，因为UEditor，单图没有好的跨域方案，你可以参考一下我在聊天室里的回答，有人问过这个问题https://gitter.im/haochuan9421/vue-ueditor-wrap/
