### ISSUE TITLE
为什么我上传图片成功后图片没有显示在编辑器里？

### ISSUE THREAD

**Issue by lilu1814** [HaoChuan9421/vue-ueditor-wrap#23]

**Comment by HaoChuan9421** [comment]
你把正确的serveUrl放在我的demo项目里，如果也出现这个问题，你再截图，说明一下重现步骤

**Comment by jinwyp** [comment]
https://haochuan9421.github.io/vue-ueditor-wrap-demo/#/Home 

你这个线上的demo 也无法上传, 提示 
请求后台配置项http错误，上传功能将不能正常使用！

**Comment by HaoChuan9421** [comment]
@jinwyp 你需要提供一个正确的serverUrl

**Comment by NicholasZhan** [comment]
为什么我配置了我司的serverUrl后  提示错误Uncaught SyntaxError: Unexpected token : 然后单图上传是disabled 多图上传显示后端配置项没有正常加载，上传插件不能正常使用

**Comment by HaoChuan9421** [comment]
@NicholasZhan 
![image](https://user-images.githubusercontent.com/5093611/47960097-a6b89700-e02f-11e8-8896-cce57e964ee0.png)

你是这种错误吗？我在README里面有说明的

**Comment by NicholasZhan** [comment]
> @NicholasZhan
> ![image](https://user-images.githubusercontent.com/5093611/47960097-a6b89700-e02f-11e8-8896-cce57e964ee0.png)
> 
> 你是这种错误吗？我在README里面有说明的

不是这种  我截图给你
 ![image](https://user-images.githubusercontent.com/17342648/47960140-f8155600-e030-11e8-9a7a-7c42d4335741.png)
配置以后  编辑器的多图上传还不能用(我看了之前的回答 单图是因为跨域不能用吧)
![image](https://user-images.githubusercontent.com/17342648/47960176-7245da80-e031-11e8-967d-ce91fbd5d37e.png)
报错如下
![image](https://user-images.githubusercontent.com/17342648/47960178-7f62c980-e031-11e8-9876-dd60a9204f5c.png)

**Comment by HaoChuan9421** [comment]
你把你们公司后端给你的`serverUrl`填在我那个[Demo](https://github.com/HaoChuan9421/vue-ueditor-wrap-demo)里，不要改其他的地方，如果还报错，就是后端配置的问题。
