### ISSUE TITLE
使用vue-cli 3配置路径后仍然一直提示加载ueditor.config.js失败

### ISSUE THREAD

**Issue by JayLee265** [HaoChuan9421/vue-ueditor-wrap#24]
使用的是vue-cli 3.0 按照文档配置路径为UEDITOR_HOME_URL: './UEditor/', webstorm中启动项目依然提示加载不到ueditor

**Comment by HaoChuan9421** [comment]
如果你的路由使用了mode:'history',使用绝对路径，不要使用相对路径

**Comment by microyulive** [comment]
大佬，history模式中配置这个绝对路径应该怎么配啊？我把UEditor放在项目根目录的public下了。然后无论设置/public/UEditor/还是/UEditor/ 都不对。。。求指导！

**Comment by microyulive** [comment]
谢谢大佬回复，我目前UEditor文件夹是放在  myapp/public/UEditor，配置的路径要变成 /myapp/UEditor/   这样吗？

**Comment by HaoChuan9421** [comment]
我说的页面地址，你把你UEditor所在的页面的地址栏截个图吧

**Comment by microyulive** [comment]
oh... 我错了  页面地址是 http://localhost/editor

**Comment by HaoChuan9421** [comment]
那你填/UEditor/试一试

**Comment by microyulive** [comment]
![image](https://user-images.githubusercontent.com/16741029/48122744-3cb02400-e2b3-11e8-88e9-f82ced1315e6.png)
目前是这样的。但是不行。。。
![image](https://user-images.githubusercontent.com/16741029/48122769-4afe4000-e2b3-11e8-9d4c-f66483e87ab1.png)

**Comment by HaoChuan9421** [comment]
稍等一下，我试一试

**Comment by microyulive** [comment]
好的 谢谢！

**Comment by HaoChuan9421** [comment]
没毛病呀？
![image](https://user-images.githubusercontent.com/5093611/48123166-37070e00-e2b4-11e8-84ad-6a18ab2f0aa7.png)
![image](https://user-images.githubusercontent.com/5093611/48123226-57cf6380-e2b4-11e8-8472-373e10b5d1d5.png)
![image](https://user-images.githubusercontent.com/5093611/48123244-6453bc00-e2b4-11e8-99c3-c6fdc3b01383.png)

**Comment by microyulive** [comment]
明白了！在页面文件里传config进去没问题，不能直接在原先的config.js文件里直接操作。谢谢大佬！

**Comment by HaoChuan9421** [comment]
OK

**Comment by microyulive** [comment]
issue可以关闭啦 谢谢！

**Comment by beevivo6** [comment]
为啥呀，我怎么改都没用？
vue-ueditor-wrap.min.js?6625:1 加载ueditor.config.js失败,请检查您的配置地址UEDITOR_HOME_URL填写是否正确!
 http://localhost:3333/static/UEditor/ueditor.config.js

**Comment by beevivo6** [comment]
![image](https://user-images.githubusercontent.com/29418930/91154270-ec0df300-e6f3-11ea-8718-32ea9ca568e9.png)

**Comment by beevivo6** [comment]
![image](https://user-images.githubusercontent.com/29418930/91154324-fb8d3c00-e6f3-11ea-9427-e491aa5f9173.png)
![image](https://user-images.githubusercontent.com/29418930/91154369-08119480-e6f4-11ea-9794-9432e62b93e1.png)

**Comment by beevivo6** [comment]
谁来帮帮我 -_-

**Comment by beevivo6** [comment]
为什么居中的图片点击空白处，图片超出了编辑器？而且不管点击哪里都没法获得焦点？这是啥bug?
![image](https://user-images.githubusercontent.com/29418930/91159811-2d55d100-e6fb-11ea-9110-d29ae075bb6a.png)
