### ISSUE TITLE
页面中存在2个组件时，操作会同时作用于两个组件，如何区分操作？

### ISSUE THREAD

**Issue by JayLee265** [HaoChuan9421/vue-ueditor-wrap#25]
因为业务需要，页面中需要放置2个editor组件，但设置其中一个组件的格式时，另一个组件也会相应修改，如何设置能够区分不同组件的不同操作？此问题同样存在于在线demo中

**Comment by HaoChuan9421** [comment]
demo是我用v-for循环出来的，绑定的数据都是同一个数据，是为了演示双向绑定的，其实他们之间是不会干扰，相互独立的。你分别绑定数据或配置就可以呀，不知道你指的互相影响是什么

**Comment by JayLee265** [comment]
`<template>
  <Form :model="formItem">
    <Divider orientation="left">商品详情</Divider>
    <FormItem>
      <vue-ueditor-wrap v-model="msg" :config="myConfig"></vue-ueditor-wrap>
    </FormItem>
    <FormItem>
      <vue-ueditor-wrap v-model="msg" :config="myConfig1"></vue-ueditor-wrap>
    </FormItem>
  </Form>
</template>

<script>
import VueUeditorWrap from 'vue-ueditor-wrap'

export default {
  name: 'goods-info-details',
  components: {
    VueUeditorWrap
  },
  data () {
    return {
      formItem: {},
      msg: '<h2><img src="http://img.baidu.com/hi/jx2/j_0003.gif"/>Vue + UEditor + v-model双向绑定</h2>',
      msg1:"fff",
      myConfig: {
        // 如果需要上传功能,找后端小伙伴要服务器接口地址
        // serverUrl: 'http://api.demo.com/ueditor/upload',
        // 你的UEditor资源存放的路径,相对于打包后的index.html(路由使用history模式注意使用绝对路径或者填写正确的相对路径)
        UEDITOR_HOME_URL: './UEditor/',
        // 编辑器不自动被内容撑高
        autoHeightEnabled: false,
        // 初始容器高度
        initialFrameHeight: 240,
        // 初始容器宽度
        initialFrameWidth: '100%',
        // 关闭自动保存
        enableAutoSave: false
      },
      myConfig1: {
        // 如果需要上传功能,找后端小伙伴要服务器接口地址
        // serverUrl: 'http://api.demo.com/ueditor/upload',
        // 你的UEditor资源存放的路径,相对于打包后的index.html(路由使用history模式注意使用绝对路径或者填写正确的相对路径)
        UEDITOR_HOME_URL: './UEditor/',
        // 编辑器不自动被内容撑高
        autoHeightEnabled: false,
        // 初始容器高度
        initialFrameHeight: 240,
        // 初始容器宽度
        initialFrameWidth: '100%',
        // 关闭自动保存
        enableAutoSave: false
      }
    }
  }
}
</script>`
我的页面代码，不知道您说的绑定统一数据是指哪里？互相影响意思就是将第一个editor中的文本居中时，第二个editor中的文本也会居中

**Comment by JayLee265** [comment]
呃，，没改掉v-model中的绑定属性，，不该这么粗心，再次感谢解惑
