### ISSUE TITLE
IE10，IE11 图片的复制黏贴好像不能用

### ISSUE THREAD

**Issue by zhangpj10** [HaoChuan9421/vue-ueditor-wrap#27]
![image](https://user-images.githubusercontent.com/31815084/47617351-527a5800-db01-11e8-9033-55d36043d498.png)
改了这边的黏贴图片的源码，也是不能用，该怎么改呢？求助

**Comment by HaoChuan9421** [comment]
这个我看了一下官方的[示例](https://ueditor.baidu.com/website/onlinedemo.html)，在IE里面也不行，我只是提供一个双向绑定的wrap，你要是自己感兴趣的话就自己改源码吧😂

**Comment by zhangpj10** [comment]
对，我之前在官方的示例里试了，也是不行，估计就只能改源码了
