### ISSUE TITLE
单图上传不成功

### ISSUE THREAD

**Issue by liruidong1** [HaoChuan9421/vue-ueditor-wrap#29]
在demo地址上测试过了 同样存在单图上传提示上传错误的问题

**Comment by HaoChuan9421** [comment]
UEditor不支持跨域单图上传，有一个取巧的方式
![image](https://user-images.githubusercontent.com/5093611/48197677-6770aa00-e391-11e8-8bcc-6a0b2d9d28d9.png)

**Comment by liruidong1** [comment]
好的 非常感谢
