### ISSUE TITLE
想请教下有关修改ueditor源码的问题

### ISSUE THREAD

**Issue by microyulive** [HaoChuan9421/vue-ueditor-wrap#30]
想请教，我看了下你的工具中是引入的ueditor.all.min.js
如果我想修改ueditor中的源码里的内容是不是只能通过改ueditor.all.js?
这样的话是不是不能生效？

**Comment by HaoChuan9421** [comment]
对，你直接改ueditor.all.js是不会生效的，也不建议你在生产环境下使用未压缩的js,给你两点建议：
1. 在index.html里通过script标签引入ueditor.config.js和ueditor.all.js，我的组件会自动判断，如果已经加载过，就不会重复加载
2. 改[项目源码](https://github.com/HaoChuan9421/ueditor)，然后打包构建，这样会生成你需要的压缩后的js,具体参考[打包文档](http://fex.baidu.com/ueditor/#dev-bale_width_grunt)。这也是我修复一些UEditor BUG使用的方式，也推荐你这么做

**Comment by microyulive** [comment]
好的 非常感谢！！！
