### ISSUE TITLE
registerButton 如何指定自定义按钮的位置？

### ISSUE THREAD

**Issue by 86chenjie** [HaoChuan9421/vue-ueditor-wrap#31]
thanks!

**Comment by HaoChuan9421** [comment]
请自行百度

**Comment by microyulive** [comment]
额 大佬 不知道他遇到的问题是不是和我一样。。我是在:init方法里执行的registerButton，
然后:config方法里加了toolbars并设置了自定义的按钮的位置。
比如:
[[ 'simpleupload', 'insertimage', 'custommusic', 'map' ]]
其中custommusic是我自定义的
但是执行后发现这个自定义按钮的位置永远在工具栏的最后一个，是不是因为百度默认是先把默认的按钮添加好 然后再加载自定义按钮的缘故？

**Comment by HaoChuan9421** [comment]
@microyulive 安装最新版本`npm i vue-ueditor-wrap@latest`, 调用方法是传一个 index 就可以了

**Comment by microyulive** [comment]
好的 非常感谢！
