### ISSUE TITLE
This relative module was not found:  * ./lib in ./node_modules/vue-ueditor-wrap/index.js

### ISSUE THREAD

**Issue by zoutong123** [HaoChuan9421/vue-ueditor-wrap#32]
![image](https://user-images.githubusercontent.com/24762954/48608590-ab7d3380-e9bd-11e8-82ff-3e3bb9fddc15.png)

**Comment by HaoChuan9421** [comment]
你尝试用cnpm或者yarn安装

**Comment by zoutong123** [comment]
![image](https://user-images.githubusercontent.com/24762954/48610003-3f9bca80-e9bf-11e8-86d0-2619b248cc41.png)
有这个模块了

**Comment by HaoChuan9421** [comment]
这个问题我也不清楚

**Comment by zoutong123** [comment]
module.exports=require('./lib/index.vue')
这样控制台不会报错，我用的脚手架是vue-cli3

**Comment by HaoChuan9421** [comment]
我也用vue-cli3试过的，没啥问题，不知道是不是电脑的原因，我的是Mac，或者是npm版本的问题,我的是6.4.1，node版本是v10.11.0。我过段时间闲了把他编译成js再发布，那样会好点。还可以直接通过链接引入，你暂时可以把index.vue直接拷贝出来用。

**Comment by zoutong123** [comment]
@HaoChuan9421 en, thank you all the same.
