### ISSUE TITLE
当使用Shift+某个按键 组合输入时 无法触发数据同步

### ISSUE THREAD

**Issue by zhangzhengyi12** [HaoChuan9421/vue-ueditor-wrap#36]
## 环境

macos 10.14.1 外接键盘

## 复现

在编辑器中使用Shift+某个按键进行输入，如输入一大串的大写英文字母，这时候和会发现没有触发$emit("input")事件，所以无法同步到数据上。如果使用大写锁定输入大写英文是可以的

对Ueditor的特性不是很了解，不知道是那里除了问题。我在自己的项目中或者是你的DEMO中测试结果相同

**Comment by zhangzhengyi12** [comment]
如果需要的话 我可以提供视频

**Comment by HaoChuan9421** [comment]
这个问题我在[常见问题 5](https://github.com/HaoChuan9421/vue-ueditor-wrap#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 里面也说过，确实存在，因为 v-model 的实现基础是 UEditor 的 contentChange 事件，按住 Shift 键时， contentChange 事件不会触发，所以也就无法 $emit("input") 导致绑定失效，如果你有解决方案，可以提交一个 PR

**Comment by zhangzhengyi12** [comment]
非常抱歉，没有仔细查看文档
