### ISSUE TITLE
如果没有文字，直接上传视频，v-model的值是空的，输入一个字符，就都有了

### ISSUE THREAD

**Issue by lv1369128582** [HaoChuan9421/vue-ueditor-wrap#38]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by HaoChuan9421** [comment]
录了个GIF，并不存在你说的问题（图片比较大，加载可以需要一会），请按照ISSUE模版，具体填写复现步骤
![qq20181226-174534-hd 1](https://user-images.githubusercontent.com/5093611/50441672-c2a52e80-0936-11e9-9792-bf81fb85f402.gif)
