### ISSUE TITLE
上传图片到七牛怎么配置，有遇见吗

### ISSUE THREAD

**Issue by beibeijerry** [HaoChuan9421/vue-ueditor-wrap#39]
ueditor.all.min.js:9 GET http://upload.qiniu.com/?action=config&callback=bd__editor__qgui58 net::ERR_ABORTED 405 (Method Not Allowed)
d @ ueditor.all.min.js:9
c @ ueditor.all.min.js:9
request @ ueditor.all.min.js:9
(anonymous) @ ueditor.all.min.js:9
setTimeout (async)
UE.Editor.loadServerConfig @ ueditor.all.min.js:9
UE.Editor @ ueditor.all.min.js:8
UE.ui.Editor @ ueditor.all.min.js:18
UE.getEditor @ ueditor.all.min.js:18
_initEditor @ vue-ueditor-wrap.min.js?6625:1
(anonymous) @ vue-ueditor-wrap.min.js?6625:1
Promise.then (async)
handler @ vue-ueditor-wrap.min.js?6625:1
Vue.$watch @ vue.runtime.esm.js?2b0e:3609
createWatcher @ vue.runtime.esm.js?2b0e:3567
initWatch @ vue.runtime.esm.js?2b0e:3549
initState @ vue.runtime.esm.js?2b0e:3313
Vue._init @ vue.runtime.esm.js?2b0e:4624
VueComponent @ vue.runtime.esm.js?2b0e:4794
createComponentInstanceForVnode @ vue.runtime.esm.js?2b0e:4306
init @ vue.runtime.esm.js?2b0e:4127
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
patch @ vue.runtime.esm.js?2b0e:6087
Vue._update @ vue.runtime.esm.js?2b0e:2656
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
init @ vue.runtime.esm.js?2b0e:4133
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
patch @ vue.runtime.esm.js?2b0e:6087
Vue._update @ vue.runtime.esm.js?2b0e:2656
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
init @ vue.runtime.esm.js?2b0e:4133
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
updateChildren @ vue.runtime.esm.js?2b0e:5841
patchVnode @ vue.runtime.esm.js?2b0e:5932
updateChildren @ vue.runtime.esm.js?2b0e:5818
patchVnode @ vue.runtime.esm.js?2b0e:5932
patch @ vue.runtime.esm.js?2b0e:6092
Vue._update @ vue.runtime.esm.js?2b0e:2666
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
run @ vue.runtime.esm.js?2b0e:3215
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:2977
(anonymous) @ vue.runtime.esm.js?2b0e:1833
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
ueditor.all.min.js:9 请求后台配置项http错误，上传功能将不能正常使用！
showErrorMsg @ ueditor.all.min.js:9
onerror @ ueditor.all.min.js:9
(anonymous) @ ueditor.all.min.js:9
error (async)
c @ ueditor.all.min.js:9
request @ ueditor.all.min.js:9
(anonymous) @ ueditor.all.min.js:9
setTimeout (async)
UE.Editor.loadServerConfig @ ueditor.all.min.js:9
UE.Editor @ ueditor.all.min.js:8
UE.ui.Editor @ ueditor.all.min.js:18
UE.getEditor @ ueditor.all.min.js:18
_initEditor @ vue-ueditor-wrap.min.js?6625:1
(anonymous) @ vue-ueditor-wrap.min.js?6625:1
Promise.then (async)
handler @ vue-ueditor-wrap.min.js?6625:1
Vue.$watch @ vue.runtime.esm.js?2b0e:3609
createWatcher @ vue.runtime.esm.js?2b0e:3567
initWatch @ vue.runtime.esm.js?2b0e:3549
initState @ vue.runtime.esm.js?2b0e:3313
Vue._init @ vue.runtime.esm.js?2b0e:4624
VueComponent @ vue.runtime.esm.js?2b0e:4794
createComponentInstanceForVnode @ vue.runtime.esm.js?2b0e:4306
init @ vue.runtime.esm.js?2b0e:4127
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
patch @ vue.runtime.esm.js?2b0e:6087
Vue._update @ vue.runtime.esm.js?2b0e:2656
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
init @ vue.runtime.esm.js?2b0e:4133
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
patch @ vue.runtime.esm.js?2b0e:6087
Vue._update @ vue.runtime.esm.js?2b0e:2656
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
init @ vue.runtime.esm.js?2b0e:4133
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
updateChildren @ vue.runtime.esm.js?2b0e:5841
patchVnode @ vue.runtime.esm.js?2b0e:5932
updateChildren @ vue.runtime.esm.js?2b0e:5818
patchVnode @ vue.runtime.esm.js?2b0e:5932
patch @ vue.runtime.esm.js?2b0e:6092
Vue._update @ vue.runtime.esm.js?2b0e:2666
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
run @ vue.runtime.esm.js?2b0e:3215
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:2977
(anonymous) @ vue.runtime.esm.js?2b0e:1833
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
4ueditor.all.min.js:8 The given range isn't in document.

**Comment by syhyz1990** [comment]
创建自定义按钮，调用前端七牛js api ，后台接口返回个token就行

**Comment by HaoChuan9421** [comment]
创建自定义按钮，前端调js api 当然可以，但原本的那些上传图片，视频，文件的各种按钮你都隐藏掉吗？后端也有接口，干嘛不用？多一次转发？但是你丢失的是百度编辑器完整的用户体验！

**Comment by syhyz1990** [comment]
> 创建自定义按钮，前端调js api 当然可以，但原本的那些上传图片，视频，文件的各种按钮你都隐藏掉吗？后端也有接口，干嘛不用？多一次转发？但是你丢失的是百度编辑器完整的用户体验！

这样你需要把图片传到后台服务器，在后台服务器上传到七牛，岂不多此一举。占用服务器带宽资源

**Comment by HaoChuan9421** [comment]
各有各的理，就看你们公司前后端谁强势了🤷‍♀️
