### ISSUE TITLE
频繁切换路由时页面报错：“获取后台配置项请求出错，上传功能将不能正常使用！”，我看页面中并没有调用ueditor.config.js中的方法。是什么原因呢？

### ISSUE THREAD

**Issue by liwen327** [HaoChuan9421/vue-ueditor-wrap#40]
每一次切换路由时并不出现这个问题，当第二次切换进这个路由时就报这个错误。

![image](https://user-images.githubusercontent.com/12168167/51153250-6afd4180-18aa-11e9-92d1-e16d5020ea64.png)

**Comment by HaoChuan9421** [comment]
这个是我提供的在线Demo，似乎并不存在你说的问题。如果你确认还是这样，请按照 ISSUE 模版提交 BUG，方便我复现。
![image](https://user-images.githubusercontent.com/5093611/51161277-c6402b80-18cc-11e9-8e09-49d287131ab4.png)

**Comment by liwen327** [comment]
刷新的时候是没有问题的，因为是单页面管理后台，第一次进去编辑是可以的，但是第二次进去再编辑就报上面那个错，上传功能就不能使用了。

**Comment by HaoChuan9421** [comment]
我上面的录屏就没有刷新呀，只是路由的切换而已，你指的第二次是什么意思？

**Comment by liwen327** [comment]
![image](https://user-images.githubusercontent.com/12168167/51163105-97798380-18d3-11e9-828f-6db813e7dfe0.png)
刷新了之后是可以上传图片的，比如说刷新之后从列表进入编辑器页面，是可以不报上面的错，可是一旦你编辑完成保存之后，再从列表页面进入到编辑器页面就会报上图的错。

**Comment by liwen327** [comment]
![image](https://user-images.githubusercontent.com/12168167/51163243-03f48280-18d4-11e9-8646-53c06b2cae4d.png)
后端返回这样的格式。

**Comment by HaoChuan9421** [comment]
你精简一下代码，能不能提供一个复现 BUG 的仓库地址

**Comment by liwen327** [comment]
git@github.com:liwen327/vue-ueditor-wrap.git
这是我刚上传的，外网可能访问会有问题，你看下里面的路由设置，是不是这里出错了

**Comment by HaoChuan9421** [comment]
@liwen327 给个邮箱，和你远程

**Comment by liwen327** [comment]
870049598@qq.com

**Comment by HaoChuan9421** [comment]
非本组件问题，已解决

**Comment by pengwangpengwang** [comment]
@HaoChuan9421 老哥，这是啥问题，咋解决的，我也碰到了这个问题
