### ISSUE TITLE
百度编辑器上传图片serverUrl改用自己公司的地址会报CORB错误

### ISSUE THREAD

**Issue by churjan** [HaoChuan9421/vue-ueditor-wrap#41]
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://dev.weboxapi.esgao.cn/controller.php?action=config&callback=bd__editor__kec58c with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

![image](https://user-images.githubusercontent.com/15041918/52833377-629d5e00-3117-11e9-9201-1088e137ec9a.png)
![image](https://user-images.githubusercontent.com/15041918/52833454-aabc8080-3117-11e9-8713-02945736c49b.png)

![image](https://user-images.githubusercontent.com/15041918/52833440-9082a280-3117-11e9-8ddd-5ac7e16e6c2f.png)

但用你测试的PHP地址却是可以的，我问了后端它这个是用原生的。
请问楼主能否提供一下测试地址php代码

**Comment by HaoChuan9421** [comment]
https://github.com/HaoChuan9421/vue-ueditor-wrap-demo/issues/3#issuecomment-436630766

**Comment by HaoChuan9421** [comment]
目测你们后端没有设置 "Access-Control-Allow-Origin"

**Comment by churjan** [comment]
@HaoChuan9421 谢谢了，问题已经解决了

**Comment by 18673227300** [comment]
@churjan 怎么设置的  我后台配置了跨域  还是获取不到接口返回的配置数据
