### ISSUE TITLE
ueditor上传800M的大视频文件提示：上传失败，请重试

### ISSUE THREAD

**Issue by liwen327** [HaoChuan9421/vue-ueditor-wrap#42]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
1. 进入编辑器 页面。
2. 点击 上传视频。
3. 选择大小为800M视频，点击开始上传。
4. 上传视频处提示：上传失败，请重试。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图
![image](https://user-images.githubusercontent.com/12168167/53217671-ea451880-3693-11e9-861c-deb056b3da57.png)

![image](https://user-images.githubusercontent.com/12168167/53217708-18c2f380-3694-11e9-8492-3b6df198d0c7.png)

**开发环境**
 - 操作系统: [e.g. mac]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by HaoChuan9421** [comment]
后端配置文件中有一个限制视频文件最大上传体积的的配置项 `videoMaxSize`
![image](https://user-images.githubusercontent.com/5093611/53217884-b9b1ae80-3694-11e9-8c8b-6622748e6079.png)

**Comment by liwen327** [comment]
![image](https://user-images.githubusercontent.com/12168167/53218547-7c025500-3697-11e9-9f77-f6beb058e156.png)
这个已经配置了，是2G

**Comment by HaoChuan9421** [comment]
那我就不清楚了，你自己去网上搜吧

**Comment by myzly2019** [comment]
我也遇到了同样的问题，大佬现在是怎么解决的
