### ISSUE TITLE
大图片的时候

### ISSUE THREAD

**Issue by luocong2016** [HaoChuan9421/vue-ueditor-wrap#45]
图片过大，无法修改图片大小

**Comment by HaoChuan9421** [comment]
你点击图片不是有一圈蓝色的线吗？那个线是可以拉伸的，你把图片拉小不就可以编辑了。。。

**Comment by luocong2016** [comment]
太大了,然后就看不到。我是脚本生成的网页，有点类似于ifram一样的脚本网页.

**Comment by HaoChuan9421** [comment]
太大了，看不见。。。。越大越看不见？你的图片总有个边界吧？你点击一下不就有蓝色的框了吗，拖动就可以缩小呀
