### ISSUE TITLE
上传视频和音频遇到的bug

### ISSUE THREAD

**Issue by zengpanzp** [HaoChuan9421/vue-ueditor-wrap#48]
我在用你的组件的时候，上传视频和音频的时候需要把这个地方改成embed,不知道你是实现的的呢？请大佬告知一下。小白感激不尽。

**Comment by HaoChuan9421** [comment]
把什么地方改成embed？你期待的行为是怎样的？实际的表现是怎么的？

**Comment by zengpanzp** [comment]
上传视频和音频后视频不能播放(上传视频后，点ueditor左上角html按钮查看html代码后再点回去视频变img了)，需要在ueditor.all.js中找到insertVideo中的imgage改成embed.当然还要在ueditor.config.js中增加embed、source支持。

**Comment by HaoChuan9421** [comment]
你指的不能播放时在编辑里面不能播放还是渲染的html里不能播放？

**Comment by zengpanzp** [comment]
是上传成功后在本地编辑器中不能 播放。

**Comment by HaoChuan9421** [comment]
编辑器里面不能播放是正常的，只要绑定值渲染的 html 能播放就可以了， UEditor 本来就是这个样子的，你要是想改，就自己折腾，重新编译源码。
![2019-03-23 17-17-20 2019-03-23 17_21_21](https://user-images.githubusercontent.com/5093611/54864280-1b4a6300-4d90-11e9-8896-13c3728483dd.gif)
