### ISSUE TITLE
自定义按钮进行上传视频到腾讯云服务器

### ISSUE THREAD

**Issue by liwen327** [HaoChuan9421/vue-ueditor-wrap#49]
自定义一个上传视频的按钮，把原来上传视频的按钮隐藏掉。使用腾讯云点播提供的web sdk上传视频到腾讯云服务器，后端只提供一个签名，然后拿到这个签名来上传视频。想用腾讯云的sdk替换webuploader上传视频，可以上传成功，但是后功后需要在编辑器中插入一个video或img标签来表示已经上传成功，怎么实现？需要改ueditor的源码？

**Comment by HaoChuan9421** [comment]
这个我不清楚，你查一下百度的 API 支持不，如果不行就改改源码

**Comment by liwen327** [comment]
@beforeInit这个方法中调用上传视频的方法，想在上传视频的方法中获取ueditor的实例，并在这个实例中调用execCommand的insertHtml方法，怎么获取？现在是每进到编辑器的页面就会创建一个新的实例。没办法固定成一个实例吗？@HaoChuan9421

**Comment by HaoChuan9421** [comment]
安装最新版本，使用 `keep-alive` 组件

**Comment by liwen327** [comment]
怎么使用这个组件

**Comment by HaoChuan9421** [comment]
自己看 demo 项目 和 keep-alive 文档

**Comment by liwen327** [comment]
不能把整个页面都缓存起来，这个是详情页面，从列表页面进去是不同的编辑的详情页面。能不能单独把vue-ueditor-wrap这个组件给缓存起来？

**Comment by HaoChuan9421** [comment]
状态管理呀

**Comment by liwen327** [comment]
![image](https://user-images.githubusercontent.com/12168167/55152328-1cfa9900-518b-11e9-9a0b-6ca17b658a0f.png)
我需要在这里把img标签插入到编辑器中，这时需要获取编辑器的实例
