### ISSUE TITLE
简直是帮了我大忙了~

### ISSUE THREAD

**Issue by anLl** [HaoChuan9421/vue-ueditor-wrap#5]
刚开始按照网上的方法来集成，各种报错，什么caller,callee啦，关键是build的时候直接内存溢出。。幸好看到了你写的这个，稍微折腾了一下，完美~~~~你要是在边上简直想要亲你一脸的口水~~。总之谢谢~

**Comment by HaoChuan9421** [comment]
能帮到你我也很开心，如果好用的话可以推荐给你的朋友
