### ISSUE TITLE
增加一个使用非压缩版js的配置

### ISSUE THREAD

**Issue by eddyzhang1986** [HaoChuan9421/vue-ueditor-wrap#50]
增加一个使用非压缩版js的配置,修改了ue的源码想配置使用，发现无此配置。

**Comment by HaoChuan9421** [comment]
你把这个 [Vue 组件](https://github.com/HaoChuan9421/vue-ueditor-wrap/blob/master/src/components/vue-ueditor-wrap.vue)，拿出来想怎么改都可以，npm 安装的不过就是把这个 Vue 组件转成了 js 而已
