### ISSUE TITLE
ueditor 跨域上传后端如何设置

### ISSUE THREAD

**Issue by lcsoftware** [HaoChuan9421/vue-ueditor-wrap#51]
vue-ueditor-wrap组件事例中，看到你提供 serverUrl : http://35.201.165.105:8000/controller.php, 可以达到跨域上传的功能，不知道后台是怎样实现的？
谢谢。

**Comment by HaoChuan9421** [comment]
常见问题4

**Comment by lcsoftware** [comment]
我的后台是nodejs (阿里的eggjs框架),我已经下载了您最新的utf8-php.zip, 而且我的后端是可以返回正确的配置的 http://localhost:7001/api/ueditor?action=config,   但在浏览器有一条警告：**Cross-Origin Read Blocking (CORB) blocked cross-origin response http://webapi:7001/api/ueditor?action=config&callback=bd__editor__c109th with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.**   ， 不知道有没有关系？

**Comment by HaoChuan9421** [comment]
后端没有设置 "Access-Control-Allow-Origin"，指定允许跨域的源即可

**Comment by lcsoftware** [comment]
非常感谢您的回复，已经成功。谢谢！
