### ISSUE TITLE
[ie10]组件加载过一次之后刷新路由,组件不加载

### ISSUE THREAD

**Issue by lixuguang** [HaoChuan9421/vue-ueditor-wrap#52]
录了个gif,麻烦看下
![2](https://user-images.githubusercontent.com/4262121/56077291-1025a880-5e0d-11e9-89ad-353ff01619d9.gif)

**Comment by SmaVivian** [comment]
我也遇到这个问题 ：360兼容模式下 IE11正常，切换到ie10显示空白  
![image](https://user-images.githubusercontent.com/13707745/56093465-ba7bf980-5efb-11e9-87c7-6fda8dc699b2.png)
![image](https://user-images.githubusercontent.com/13707745/56093470-cc5d9c80-5efb-11e9-9473-62ecdeb7fb44.png)

**Comment by lixuguang** [comment]
> 我也遇到这个问题 ：360兼容模式下 IE11正常，切换到ie10显示空白
> ![image](https://user-images.githubusercontent.com/13707745/56093465-ba7bf980-5efb-11e9-87c7-6fda8dc699b2.png)
> ![image](https://user-images.githubusercontent.com/13707745/56093470-cc5d9c80-5efb-11e9-9473-62ecdeb7fb44.png)

你是在ie10首次就不加载么，原生ie10打开是不是也和我一样

**Comment by SmaVivian** [comment]
我没有原生ie10，从别的页面点进来首次进来是好的，手动刷新就变空白了，再次进来都是空白

**Comment by zhangxiaoru** [comment]
怎么解决的呢，我也有这个问题

**Comment by HaoChuan9421** [comment]
2.5.3 版本修复了，IE10 亲测可用的，可以用 http://ueditor.gitrr.com/#/ 试一试
