### ISSUE TITLE
debug!!!vue-cli3 public的问题

### ISSUE THREAD

**Issue by CleverLinC** [HaoChuan9421/vue-ueditor-wrap#53]
vue-cli3的目录必须这样... 最快的解决方法,可能我比较菜
![image](https://user-images.githubusercontent.com/38413949/56198830-43b33d80-606e-11e9-9ab0-b0164252ef1a.png)

**Comment by readygosports** [comment]
哈哈 找不到那里该配置 这个是个好办法

**Comment by wangkaiChen1118** [comment]
这个真是个好方法，给劲

**Comment by zy201114** [comment]
看不到图片呢

**Comment by BNK-ALONG** [comment]
棒，成功解决问题

**Comment by ougege** [comment]
优秀，找了好久，终于得见阳光
