### ISSUE TITLE
添加大图,点击大图出现蓝色线会偏移，在点击同级文字会点击不了

### ISSUE THREAD

**Issue by anick-xs** [HaoChuan9421/vue-ueditor-wrap#54]
**你遇到了什么 BUG**
简单描述你遇到的 BUG。

**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by sowee121** [comment]
上传大图，若大图的高度超过了编辑器的高度，鼠标点击图片，出现的蓝框，会浮在页面的上层，溢出编辑器，蓝框的起始位置可能会存在偏移（即没有与图片顶部位置对齐）

**Comment by webylb** [comment]
我这边 图片的操作按钮 都定位偏了 而且蓝线执行缩放也有问题
