### ISSUE TITLE
多图上传的时候，弹框中的样式无法加载

### ISSUE THREAD

**Issue by webengineergh** [HaoChuan9421/vue-ueditor-wrap#57]
ueditor.all.min.js?8411:7 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/static/UE/static/UE/themes/default/dialogbase.css?cache=0.3896635946016489".
(anonymous) @ ueditor.all.min.js?8411:7
(anonymous) @ VM33978 internal.js:33
(anonymous) @ VM33978 internal.js:80

**Comment by webylb** [comment]
目录问题吧
