### ISSUE TITLE
垃圾项目，能别发广告吗？

### ISSUE THREAD

**Issue by callmewhy** [HaoChuan9421/vue-ueditor-wrap#6]
太脏了。

**Comment by HaoChuan9421** [comment]
首先对打扰到你们的个人生活再次表示抱歉，群发邮件确实是一种不礼貌或者在您看来有点脏。我个人可能并没有您那么优秀的个人技术或者丰富的开源经验。我写的这个项目在您看来也许很差劲。但是这一个月来确实也帮助了一些朋友解决的他们的问题。也许对您来讲，配置一些东西很简单甚至不值一提，但是搜索这一块，百度或谷歌的东西，并没有很理想的答案。我想也许那些关注Ueditor仓库的人也会在项目中遇到和我一样的问题，何不把自己踩过的坑分享给大家，毕竟还有那么多小白，而且让我欣喜的是，还有朋友发来感谢的邮箱和ISSUE,这个过程让我也体会到了开源的乐趣。于是，我就利用Github的v3的Api,抓取了关注Ueditor仓库的人的全部邮箱，并且给大家群发邮件，我承认自己是有一定的私心，希望可以有一个更多star的项目，但是我在邮件中也有说过，希望可以给各位的开发带来一点点便利。如果打扰到您的生活了，我再次诚恳说一声抱歉。这个Issue对我个人来讲，多多少少也是一个打击，毕竟这些东西都是对外的，如果有幸，希望可以听到您的意见或建议，我在前端甚至Coding的路上还会一直前行，我日后也想写出更优秀的东西，到时候也许感谢的邮箱会更多一些，再次对打扰您的生活表示抱歉。

**Comment by callmewhy** [comment]
兄弟，乐于分享是好事，但是不要强制别人去分享。开源的乐趣在于参与感，群发邮件这种强制博取关注是没有意义的。道理我相信你都懂，我并没有否认这个项目的价值，我只是拒绝这种传播项目的方式。
好的东西自然会发光，不用急于求成。

**Comment by HaoChuan9421** [comment]
本来打了很多字，但是总之一句话吧，谢谢您的建议，我会让别人看到更优秀的东西的💪。
