### ISSUE TITLE
好像不支持typescript类型的项目

### ISSUE THREAD

**Issue by xielicheng** [HaoChuan9421/vue-ueditor-wrap#63]
typescript项目引入依赖报错。
项目是用vue cli 3.x创建的。

![image](https://user-images.githubusercontent.com/25046207/58645007-0ca29e00-8335-11e9-86ef-27af4ba504af.png)

**Comment by Shaun-Li** [comment]
而且想自己写个d.ts，一看vue-ueditor-wrap.min.js却是压缩过的......

**Comment by PythonNaChen** [comment]
最后解决了吗

**Comment by PythonNaChen** [comment]
> 而且想自己写个d.ts，一看vue-ueditor-wrap.min.js却是压缩过的......

// @ts-ignore
import VueUeditorWrap from 'vue-ueditor-wrap'
通过注释直接忽略导入插件的类型校验即可
