### ISSUE TITLE
如何配置 options.headers 

### ISSUE THREAD

**Issue by ibmsoft** [HaoChuan9421/vue-ueditor-wrap#68]
我看 image.js 中有以下代码
 if(editor.options.headers && Object.prototype.toString.apply(editor.options.headers) === "[object Object]"){
                    for(var key in editor.options.headers){
                        header[key] = editor.options.headers[key]
                    }
                }

怎么配置 options.header  这个参数
放到 config 里，不起作用

**Comment by ibmsoft** [comment]
知道了，在config 中直接设置 header

**Comment by HaoPengZheng** [comment]
我也遇到了这样的问题，请问能否举例一下？

**Comment by yongxinz** [comment]
> 知道了，在config 中直接设置 header

请问是如何配置的，能否举个例子？如果是携带 COOKIE，能否用同样的方式配置？

**Comment by yongxinz** [comment]
> 我也遇到了这样的问题，请问能否举例一下？

请问你的问题解决了吗？

**Comment by zhujinhu21** [comment]
config 中设置了 header: { 'Authorization:': 'Bearer ' + getToken() }, 不起作用

**Comment by cactus1949** [comment]
你好，我遇到个问题，也是config里的配置项，customstyle，不起作用
