### ISSUE TITLE
修改输入内容以后获取到的内容，还是初始化的时候绑定的值

### ISSUE THREAD

**Issue by qmt216** [HaoChuan9421/vue-ueditor-wrap#73]
修改输入内容以后获取到的内容，还是初始化的时候绑定的值

**如何复现**
复现 BUG 的步骤:
我的场景是修改文章，修改的时候先会吧文章的内容复制给编辑器，然后修改以后，发现获取到的内容还是以前赋值的内容

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断是组件的bug

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
无

**开发环境**
 - 操作系统: Win10
 - 浏览器: 谷歌75
 - 组件版本:  v2.4.1
 - 是否使用了本仓库下载的 UEditor 资源文件:  是
 - 是否使用了我提供的 serverUrl:  否

**附件说明**
目前在开发环境很难重现，但是build以后非常容易重现

**Comment by tidows** [comment]
用watch 监听试试！

**Comment by sd4888108** [comment]
是因为你的对象字段  例如 {content:null}  导致的 需要明确的给一个空  {content:''}
