### ISSUE TITLE
serverUrl与页面访问域名一致时获取config不会带callback参数

### ISSUE THREAD

**Issue by 941477276** [HaoChuan9421/vue-ueditor-wrap#74]
**你遇到了什么 BUG**
当serverUrl与页面访问域名一致时获取config不会带callback参数

**错误的参数**
比如页面访问地址为：`http://47.234.122.126:1234`
serverUrl地址为：`http://47.234.122.126:1234`
那么ueditor初始化时获取参数的请求就会变成：
`http://47.234.122.126:1234//ueditor/upload?action=config&&noCache=1565088196351`

![image](https://user-images.githubusercontent.com/20528541/62534314-6bc3e800-b87b-11e9-992f-5c57a7a382a3.png)

**正确的参数**
比如页面访问地址为：`http://47.234.122.126:1234`
serverUrl地址为：`http://47.234.122.126:456`
那么ueditor初始化时获取参数的请求就会变成：
`http://47.234.122.126:456/ueditor/upload?action=config&callback=bd__editor__4eodey`

![image](https://user-images.githubusercontent.com/20528541/62534379-96ae3c00-b87b-11e9-88b6-b89a644828bd.png)

**是 UEditor 的 BUG 还是组件的 BUG**
感觉有可能是 vue-ueditor-wrap 组件 的问题

**Comment by goodrufu** [comment]
没有callback应该不是同域名的问题，而是serverUrl没有http开头的问题，因为没有http开头，所以ueditor默认不是http请求，而是获取本地文件，所以会报错。修改源码即可，在ueditor.all.js文件下

8090行，强改即可（注意，改库引用的是min.js文件，所以得去min.js改
）：

var configUrl = window.location.origin + me.getActionUrl('config'),
                    isJsonp = true || utils.isCrossDomainUrl(configUrl);

**Comment by 941477276** [comment]
问题已解决，确实是如@goodrufu所说，直接在`ueditor.all.min.js`文件中改代码即可。但根本问题还是没解决，我正式环境的`serverUrl`也是使用的绝对路径(即http开头的)，ueditor在发送请求时依然没有带`callback`参数

**Comment by Ae86fast** [comment]
> 问题已解决，确实是如@goodrufu所说，直接在`ueditor.all.min.js`文件中改代码即可。但根本问题还是没解决，我正式环境的`serverUrl`也是使用的绝对路径(即http开头的)，ueditor在发送请求时依然没有带`callback`参数

请你问你是怎么解决的

**Comment by 941477276** [comment]
serverUrl使用绝对路径呀，你网站是http还是https的，要区分开来
