### ISSUE TITLE
怎么设置 header 里的token

### ISSUE THREAD

**Issue by Mradxz** [HaoChuan9421/vue-ueditor-wrap#76]
RT.

**Comment by usluckily** [comment]
同问

**Comment by HaoChuan9421** [comment]
@usluckily 看 [Demo](https://github.com/HaoChuan9421/vue-ueditor-wrap-demo/blob/master/src/components/Home.vue) 项目，里面有
![image](https://user-images.githubusercontent.com/5093611/71663753-610d7080-2d91-11ea-9722-336f3655908d.png)

**Comment by usluckily** [comment]
@HaoChuan9421  学到了，感谢
