### ISSUE TITLE
IE11 在编辑器里不断输入文字，会出现内容被清空的情况；输入英文会各种随机换行；

### ISSUE THREAD

**Issue by xiaYong-web** [HaoChuan9421/vue-ueditor-wrap#77]
**你遇到了什么 BUG**
IE11浏览器 在编辑器里不断输入文字，会出现内容被清空的情况

**如何复现**
复现 BUG 的步骤:
1. 进入您提供的DOME页面。
2. 在编辑器里比较快速的输入任何文字内容。
4. 出现输入的内容会被情况的情况。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为vue-ueditor-wrap 组件 双向绑定 导致的报错

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g.  IE11 ]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g.  是]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**Comment by xhfHIT** [comment]
我也遇到了，ueditor百度官方没有问题的，这边demo在IE上，不断输入英文字符，会自动换行。

**Comment by xiaYong-web** [comment]
> 英文字符，会自

**Comment by xiaYong-web** [comment]
后续解决了吗?!!

**Comment by HaoChuan9421** [comment]
自动换行在 2.5.3 版本修复了，可以用 http://ueditor.gitrr.com/#/ 试一试
