### ISSUE TITLE
封装以后如何调用原生的detroy方法？

### ISSUE THREAD

**Issue by waveheart** [HaoChuan9421/vue-ueditor-wrap#8]
封装以后的实例上找不到原生的方法
在以下场景会报错
绑定的value，在跳转新页面前有时候会做清空操作，这时候value的值发生变化，但是Ueditor的绑定是一个异步过程，此时页面已销毁，找不到UE实例，DOM渲染会出错

Uncaught TypeError: Cannot set property 'innerHTML' of null
    at baidu.editor.ui.Message.setContent (ueditor.all.min.js:17)
    at baidu.editor.ui.Message.reset (ueditor.all.min.js:17)
    at UE.Editor.<anonymous> (ueditor.all.min.js:18)
    at UE.Editor.fireEvent (ueditor.all.min.js:7)
    at UE.Editor.trigger (ueditor.all.min.js:7)
    at ueditor.all.min.js:18

**Comment by waveheart** [comment]
问题补充： 应该是由keep-alive引起的。ueditor的内容做的本地存储。不在keep-alive之内

**Comment by HaoChuan9421** [comment]
这个和`keep-alive`关系不大，主要原因是`autoSave`。
<img width="210" alt="qq20180711-174630 2x" src="https://user-images.githubusercontent.com/28668354/42564107-7503e51e-8532-11e8-8385-4bc177bf9a79.png">
Ueditor默认配置是每次`contentChange`的500ms后自动保存编辑器内容到`localStorage`
<img width="622" alt="qq20180711-162148 2x" src="https://user-images.githubusercontent.com/28668354/42564140-8ce07bc0-8532-11e8-9621-267cb08fbbe0.png">
&emsp;当你跳转路由的时候，挂在this上的editor实例已经被销毁，但是异步的`autoSave`还是会执行，此时就会出现各种`null`的错误。如果我没猜错的，这种报错的时机是：你刚输入完内容，编辑器右上角还没有出现`本地保存成功`的提示,你就点击跳转路由了。这种报错对你项目不会有太大影响.
&emsp;所以只要把没什么卵用的`autoSave`关闭即可，但是`ueditor`的1.4.3.3版本`enableAutoSave: false`是无效的，所以我重新编译了`1.5.0`的版本并把资源文件放在了`dist`目录下，你可以下载替换，`README.md`我也更新了。
&emsp;我也在组件的`beforeDestory`钩子里调用了实例的`destory`方法（其实没什么用，只是把大部分实例属性销毁并换成textarea），如果你想更新的话，可以执行`npm i vue-ueditor-wrap@1.3.1`
&emsp;当然还有一种取巧的方式，你把自动保存的周期设置的非常大也可以。

**Comment by waveheart** [comment]
完美，谢谢大佬，大佬牛逼，大佬six six six!

**Comment by caiya** [comment]
怎么我使用的时候每次刷新页面都会报错：
![image](https://user-images.githubusercontent.com/12036572/42930146-ce2ab568-8b6e-11e8-9984-3405f599a65a.png)

第一次打开却是ok的不报错呢

**Comment by dsnzts** [comment]
我想让它能自动保存，又不想跳转页面的时候报各种null错误，我该咋办呢？求解！谢谢！
