### ISSUE TITLE
如何引用外部javascript

### ISSUE THREAD

**Issue by vintail** [HaoChuan9421/vue-ueditor-wrap#81]
有个问题想询问下，ueditor该怎样引用第三方的js脚本，以便增强iframe内的dom操作？

**Comment by zzhenxiang** [comment]
找到引入第三方的js脚本的方法了吗？

**Comment by HaoChuan9421** [comment]
新增了 [editor-dependencies](https://github.com/HaoChuan9421/vue-ueditor-wrap#editor-dependencies-%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E) 属性
