### ISSUE TITLE
保存之后怎么在组件内解析啊，不解析样式会错乱，没背景，表格没边框啥的

### ISSUE THREAD

**Issue by 781499682ll** [HaoChuan9421/vue-ueditor-wrap#84]
**你遇到了什么 BUG**
保存之后怎么在组件内解析啊，不解析样式会错乱，没背景，表格没边框啥的

**如何复现**
复现 BUG 的步骤:
1. 完成编辑上传。
2. 接口返回渲染。
3. 部分样式未生效，需要另设uParse解析。

![image](https://user-images.githubusercontent.com/43060542/65139813-da31c380-da3f-11e9-9c54-a03b937e84c7.png)

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**额外说明**
你的示例也存在未解析的问题

**Comment by hongz1125** [comment]
uparse 方法怎么调用呢？

**Comment by 781499682ll** [comment]
> uparse 方法怎么调用呢？
组件内引入就好了
import "../../../../../public/UEditor/ueditor.config.js";
import "../../../../../public/UEditor/ueditor.all.min.js";
import "../../../../../public/UEditor/lang/zh-cn/zh-cn.js";
import  "../../../../../public/UEditor/ueditor.parse.js";
如果要按需渲染需要改下ueditor.parse.js源码(#^.^#)
