### ISSUE TITLE
serverUrl地址需要token验证

### ISSUE THREAD

**Issue by zhujinhu21** [HaoChuan9421/vue-ueditor-wrap#89]
**你遇到了什么 BUG**
 config 中配置了 header: { 'Authorization:': 'Bearer ' + getToken() },不起作用，提示401 unauthorized。我看了https://github.com/HaoChuan9421/vue-ueditor-wrap/issues/68 ，说是在config中配置header.

**如何复现**
复现 BUG 的步骤:
1. 进入 xxx 页面。
2. 点击 xxx。
3. 输入 xxx。
4. 出现报错 xxx。

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断一下是因为 UEditor 导致的报错，还是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
如果可能，提供截图

**开发环境**
 - 操作系统: [e.g. Win10]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. http://35.201.165.105:8000/controller.php]

**额外说明**
如果可能请提供一个复现问题的 GitHub 仓库地址

**Comment by cheneyjuu** [comment]
我刚刚从Google进入了你的问题，不知道你的问题解决了没有。
如果没有，希望我可以帮到你:
在`ueditor/dialogs/image/image.js`文件中，大概在707行，这里可以添加`token`。

```
uploader.on('uploadBeforeSend', function (file, data, header) {
                //这里可以通过data对象添加POST参数
                var token = window.localStorage.getItem('_token') || '';
    if (token) {
       header['Authorization']='Bearer '+ JSON.parse(token).token;
    }
                header['X_Requested_With'] = 'XMLHttpRequest';
            });
```
