### ISSUE TITLE
频繁切换页面时报错

### ISSUE THREAD

**Issue by msevensun** [HaoChuan9421/vue-ueditor-wrap#9]
报错信息：
![image](https://user-images.githubusercontent.com/20658340/42673372-aa963c9c-869d-11e8-8b6b-dc710e46a7d4.png)
此报错会阻塞路由的跳转。
另外频繁切换时还会有其他报错：
![image](https://user-images.githubusercontent.com/20658340/42673418-f5bea2ea-869d-11e8-8a96-86d17c207569.png)
请问如何解决？

**Comment by HaoChuan9421** [comment]
你的第一个报错我不太清楚，也没有重现出来。第二个报错的确实和频繁切换路由有关系,准确来说这个时机应该是你从没有UEditor的路由切换到UEditor所在页面，又迅速切换走(500ms内)。这个报错和UEditor的消息提示message有关系
![image](https://user-images.githubusercontent.com/28668354/42735572-024bf37c-8889-11e8-849a-fc8bb93f56c9.png)
![image](https://user-images.githubusercontent.com/28668354/42735575-0fd7aa4a-8889-11e8-89b5-0b1cd43c2e02.png)
UEditor会在监听到实例ready之后设置消息提示元素的位置，但是又在500ms之后再次设置。当你切换走了，这个异步的代码仍然在执行，而在组件的beforeDestory钩子里，调用了实例的destroy方法，导致实例的ui属性被销毁了，也就会出现`‘getDom’ of undefined`的报错。
解决这个问题我认为有两个办法，
一个办法是在你的页面组件的beforeRouteLeave路由钩子里设置定时器，大于500ms,然后调用next()方法让路由跳走（不推荐，有明显延迟感）。
![image](https://user-images.githubusercontent.com/28668354/42735626-1b7ff75c-888a-11e8-98b4-19ba7335a091.png)
另一个方法就是把源码里500ms的延迟给关闭，我并不清楚原作者设置这个定时器的目的，但是发现关闭之后，并不会导致消息提示元素的位置错乱，而且在showmessage的事件监听中，源码里也再次调用了updateHolderPos方法，所以我选择直接修改[源码](https://github.com/HaoChuan9421/ueditor/commits/dev-1.4.3.3)，并把重新编译后的文件放到[dist](https://github.com/HaoChuan9421/vue-ueditor-wrap/tree/master/dist)目录下。除此之外一些其他的异步代码或逻辑不严谨可能导致的报错，我也对源码进行了调整。

这是[演示DEMO](https://haochuan9421.github.io/vue-ueditor-wrap-demo/#/Home),你可以测试一下

**Comment by hotyann** [comment]
**你好，请问点击 “撤销” 和 “取消撤销” 会报错 _“The given range isn't in document.”_
有什么方法能避免嘛_(:з」∠)_**
<br/>
![bug](https://user-images.githubusercontent.com/24471519/42924742-236100e8-8b5e-11e8-9a57-0a2868f9fe28.png)
