### ISSUE TITLE
"TypeError: Cannot set property 'id' of undefined"

### ISSUE THREAD

**Issue by wswax** [HaoChuan9421/vue-ueditor-wrap#91]
**你遇到了什么 BUG**
引用完毕之后，控制台报错"TypeError: Cannot set property 'id' of undefined"，且编辑器不显示

**是 UEditor 的 BUG 还是组件的 BUG**
初步判断是由于本仓库的 vue-ueditor-wrap 组件导致的报错。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**
<img width="773" alt="WeChat7dbb69bf3c787d239c07758575c711d4" src="https://user-images.githubusercontent.com/8621486/67553064-f0b5f380-f73e-11e9-8b83-0d9d9d024def.png">

**开发环境**
 - 操作系统: MacBook Pro 10.13.6
 - 浏览器:  Chrome 77.0.3865.120（正式版本） （64 位）
 - 组件版本:  v2.4.1
 - 是否使用了本仓库下载的 UEditor 资源文件:  是
 - 是否使用了我提供的 serverUrl: 是

**Comment by Bennyliu701** [comment]
同问。。。

**Comment by Bennyliu701** [comment]
试出来了，serverUrl: "", 上传文件接口先默认传空就行了

**Comment by zhouxitian** [comment]
一样的问题。serverUrl默认传空也不行，最后解决了么

**Comment by zhouxitian** [comment]
一样的问题。serverUrl传空也不行。可能是组件的代码还没完成加载就已经开始初始化了(例如用在弹窗里)，所以报错，延迟一下组件的加载就好，如先用v-if隐藏，然后在this.$nextTick里再显示出来。

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
