### ISSUE TITLE
初始化时报not import language file错误

### ISSUE THREAD

**Issue by tonyxiaomao** [HaoChuan9421/vue-ueditor-wrap#96]
打开页面时报not import language file错误

复现 BUG 的步骤:
1. 进入 xxx 页面。
不是一直发生，偶发性，估计是异步加载有关。

初步判断一下是因为 UEditor 导致的报错，看了源码获取this.options时lang这个属性没有。

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

![image](https://user-images.githubusercontent.com/1740887/69614877-e7d27d80-106e-11ea-84f0-e6c695233103.png)

**开发环境**
 - 操作系统: macOS
 - 浏览器:  谷歌 Version 78.0.3904.108
 - 组件版本:  php版
 - 是否使用了本仓库下载的 UEditor 资源文件:  是
 - 是否使用了我提供的 serverUrl:  否
 - VueCLi版本：3.X

**Comment by cgd199158** [comment]
请问这个问题如何解决的?

**Comment by Alan-QK** [comment]
请问这个问题解决了吗 ？
