### ISSUE TITLE
关于“assets/downloads/”文件无法下载

### ISSUE THREAD

**Issue by sprogjavasprog** [HaoChuan9421/vue-ueditor-wrap#98]
**你遇到了什么 BUG**
“assets/downloads/”文件无法下载,另外使用官方的文档，当文本显示的数据过多（html）时，会出现”Maximum call stack size exceeded"错误导致无法显示

**如何复现**
复现 BUG 的步骤:
无

**是 UEditor 的 BUG 还是组件的 BUG**
无

**你是否查阅了 README 中的常见问题和其他 ISSUE**
已查阅，没有发现我遇到的问题

**截图**

**开发环境**
 - 操作系统: [e.g. Win7]
 - 浏览器:  [e.g. 谷歌 71.0.3578.98 版本]
 - 组件版本:  [e.g. v2.3.0]
 - 是否使用了本仓库下载的 UEditor 资源文件:  [e.g. 否]
 - 是否使用了我提供的 serverUrl:  [e.g. 否]

**额外说明**

**Comment by HaoChuan9421** [comment]
毕竟有墙。去这里下载吧 https://hc199421.gitee.io/vue-ueditor-wrap
