### ISSUE TITLE
按照步骤操作后 报错说没有注册组件

### ISSUE THREAD

**Issue by zy201114** [HaoChuan9421/vue-ueditor-wrap#99]
错误信息如下：[Vue warn]: Unknown custom element: <vue-ueditor-wrap> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
请问各位大佬这个怎么解决

**Comment by HaoChuan9421** [comment]
提供一个能复现你这个问题在线 Demo 或 GitHub 仓库。

[在线 Demo 模版](https://codesandbox.io/s/uestq)
[GitHub 仓库模版](https://github.com/HaoChuan9421/vue-ueditor-wrap-v2-demo)
